MLIR: mlir::MultiAffineFunction Class Reference
mlir::MultiAffineFunction Class Reference
This class represents a multi-affine function whose domain is given by an IntegerPolyhedron.
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
MultiAffineFunction (const IntegerPolyhedron &domain, const Matrix &output)
MultiAffineFunction (const Matrix &output, unsigned numDims, unsigned numSymbols=0, unsigned numLocals=0)
~MultiAffineFunction () override=default
Kind getKind () const override
Return the kind of this IntegerPolyhedron.
bool classof (const IntegerPolyhedron *poly) const
unsigned getNumInputs () const
unsigned getNumOutputs () const
bool isConsistent () const
const IntegerPolyhedron & getDomain () const
bool hasCompatibleDimensions (const MultiAffineFunction &f) const
The hasCompatibleDimensions functions don't check the number of local ids; functions are still compatible if they have differing number of locals.
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1) override
Insert num identifiers of the specified kind at position pos.
void swapId (unsigned posA, unsigned posB) override
Swap the posA^th identifier with the posB^th identifier.
void removeIdRange (unsigned idStart, unsigned idLimit) override
Remove the specified range of ids.
void eliminateRedundantLocalId (unsigned posA, unsigned posB) override
Eliminate the posB^th local identifier, replacing every instance of it with the posA^th local identifier.
bool isEqualWhereDomainsOverlap (MultiAffineFunction other) const
Return whether the outputs of this and other agree wherever both functions are defined, i.e., the outputs should be equal for all points in the intersection of the domains.
bool isEqual (const MultiAffineFunction &other) const
Return whether the this and other are equal.
Optional< SmallVector< int64_t, 8 > > valueAt (ArrayRef< int64_t > point) const
Get the value of the function at the specified point.
void print (raw_ostream &os) const
void dump () const
Additional Inherited Members
Protected Types inherited from mlir::IntegerPolyhedron
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints, Kind::MultiAffineFunction, Kind::IntegerPolyhedron }
All derived classes of IntegerPolyhedron.
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Protected Types inherited from mlir::PresburgerSpace
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
Protected Member Functions inherited from mlir::IntegerPolyhedron
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void printSpace (raw_ostream &os) const
Prints the number of constraints, dimensions, symbols and locals in the IntegerPolyhedron.
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
std::unique_ptr< IntegerPolyhedron > clone () const
virtual void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0)
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const IntegerPolyhedron &other)
Appends constraints from other into this.
bool isEqual (const IntegerPolyhedron &other) const
Return whether this and other are equal.
bool isSubsetOf (const IntegerPolyhedron &other) const
Return whether this is a subset of the given IntegerPolyhedron.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
Optional< SmallVector< Fraction, 8 > > getRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
virtual void clearAndCopyFrom (const IntegerPolyhedron &other)
Replaces the contents of this IntegerPolyhedron with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Optional< uint64_t > computeVolume () const
Compute an overapproximation of the number of integer points in the polyhedron.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< presburger_utils::MaybeLocalRepr > &repr) const
Find equality and pairs of inequality contraints identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< presburger_utils::MaybeLocalRepr > &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const IntegerPolyhedron &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (IntegerPolyhedron &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void print (raw_ostream &os) const
void dump () const
Protected Member Functions inherited from mlir::PresburgerLocalSpace
PresburgerLocalSpace (unsigned numDims, unsigned numSymbols, unsigned numLocals)
unsigned getNumLocalIds () const
Protected Member Functions inherited from mlir::PresburgerSpace
PresburgerSpace (unsigned numDims, unsigned numSymbols)
virtual ~PresburgerSpace ()=default
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Static Protected Member Functions inherited from mlir::IntegerPolyhedron
static IntegerPolyhedron getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Protected Attributes inherited from mlir::IntegerPolyhedron
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes inherited from mlir::IntegerPolyhedron
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
This class represents a multi-affine function whose domain is given by an IntegerPolyhedron.
This can be thought of as an IntegerPolyhedron with a tuple of integer values attached to every point in the polyhedron, with the value of each element of the tuple given by an affine expression in the ids of the polyhedron. For example we could have the domain
(x, y) : (x >= 5, y >= x)
and a tuple of three integers defined at every point in the polyhedron:
(x, y) -> (x + 2, 2*x - 3y + 5, 2*x + y).
In this way every point in the polyhedron has a tuple of integers associated with it. If the integer polyhedron has local ids, then the output expressions can use them as well. The output expressions are represented as a matrix with one row for every element in the output vector one column for each id, and an extra column at the end for the constant term.
Checking equality of two such functions is supported, as well as finding the value of the function at a specified point. Note that local ids in the domain are not yet supported for finding the value at a point.
Definition at line 45 of file PWMAFunction.h.
Constructor & Destructor Documentation
MultiAffineFunction() [1/2]
mlir::MultiAffineFunction::MultiAffineFunction (const IntegerPolyhedron & domain, const Matrix & output) inline
Definition at line 56 of file PWMAFunction.h.
MultiAffineFunction() [2/2]
mlir::MultiAffineFunction::MultiAffineFunction (const Matrix & output, unsigned numDims, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Definition at line 58 of file PWMAFunction.h.
References ~MultiAffineFunction().
~MultiAffineFunction()
mlir::MultiAffineFunction::~MultiAffineFunction () override default
Referenced by MultiAffineFunction().
Member Function Documentation
classof()
bool mlir::MultiAffineFunction::classof (const IntegerPolyhedron * poly) const inline
Definition at line 64 of file PWMAFunction.h.
References mlir::IntegerPolyhedron::getKind(), and mlir::IntegerPolyhedron::MultiAffineFunction.
dump()
void MultiAffineFunction::dump () const
Definition at line 76 of file PWMAFunction.cpp.
References mlir::PWMAFunction::print().
Referenced by mlir::PWMAFunction::getPiece().
eliminateRedundantLocalId()
void MultiAffineFunction::eliminateRedundantLocalId (unsigned posA, unsigned posB) override virtual
Eliminate the posB^th local identifier, replacing every instance of it with the posA^th local identifier.
This should be used when the two local variables are known to always take the same values.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 101 of file PWMAFunction.cpp.
References mlir::IntegerPolyhedron::eliminateRedundantLocalId().
getDomain()
const IntegerPolyhedron& mlir::MultiAffineFunction::getDomain () const inline
Definition at line 73 of file PWMAFunction.h.
References hasCompatibleDimensions(), and insertId().
Referenced by mlir::PWMAFunction::addPiece(), mlir::PWMAFunction::getPiece(), isEqual(), and isEqualWhereDomainsOverlap().
getKind()
Kind mlir::MultiAffineFunction::getKind () const inline override virtual
Return the kind of this IntegerPolyhedron.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 63 of file PWMAFunction.h.
References mlir::IntegerPolyhedron::MultiAffineFunction.
getNumInputs()
unsigned mlir::MultiAffineFunction::getNumInputs () const inline
Definition at line 68 of file PWMAFunction.h.
References mlir::PresburgerSpace::getNumDimAndSymbolIds().
getNumOutputs()
unsigned mlir::MultiAffineFunction::getNumOutputs () const inline
Definition at line 69 of file PWMAFunction.h.
References mlir::Matrix::getNumRows().
Referenced by hasCompatibleDimensions(), and mlir::PWMAFunction::hasCompatibleDimensions().
hasCompatibleDimensions()
bool MultiAffineFunction::hasCompatibleDimensions (const MultiAffineFunction & f) const
The hasCompatibleDimensions functions don't check the number of local ids; functions are still compatible if they have differing number of locals.
Definition at line 183 of file PWMAFunction.cpp.
References mlir::PresburgerSpace::getNumDimIds(), getNumOutputs(), mlir::PWMAFunction::getNumOutputs(), and mlir::PresburgerSpace::getNumSymbolIds().
Referenced by getDomain(), and mlir::PWMAFunction::getPiece().
insertId()
unsigned MultiAffineFunction::insertId (IdKind kind, unsigned pos, unsigned num = 1) override virtual
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. The coefficient columns corresponding to the added identifiers are initialized to zero. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 84 of file PWMAFunction.cpp.
Referenced by getDomain().
isConsistent()
bool mlir::MultiAffineFunction::isConsistent () const inline
Definition at line 70 of file PWMAFunction.h.
References mlir::Matrix::getNumColumns(), and mlir::PresburgerSpace::getNumIds().
Referenced by mlir::PWMAFunction::addPiece().
isEqual()
bool MultiAffineFunction::isEqual (const MultiAffineFunction & other) const
Return whether the this and other are equal.
This is the case if they lie in the same space, i.e. have the same dimensions, and their domains are identical and their outputs are equal on their domain.
Definition at line 78 of file PWMAFunction.cpp.
References getDomain(), mlir::PWMAFunction::getDomain(), mlir::PWMAFunction::hasCompatibleDimensions(), and mlir::PresburgerSet::isEqual().
Referenced by mlir::PWMAFunction::getPiece().
isEqualWhereDomainsOverlap()
bool MultiAffineFunction::isEqualWhereDomainsOverlap (MultiAffineFunction other) const
Return whether the outputs of this and other agree wherever both functions are defined, i.e., the outputs should be equal for all points in the intersection of the domains.
Definition at line 107 of file PWMAFunction.cpp.
References mlir::IntegerPolyhedron::addEquality(), getDomain(), mlir::PWMAFunction::getNumOutputs(), mlir::Matrix::getRow(), mlir::PWMAFunction::hasCompatibleDimensions(), mlir::IntegerPolyhedron::isSubsetOf(), mlir::IntegerPolyhedron::mergeLocalIds(), and subtract().
print()
void MultiAffineFunction::print (raw_ostream & os) const
Definition at line 68 of file PWMAFunction.cpp.
References mlir::IntegerPolyhedron::print().
Referenced by mlir::PWMAFunction::getPiece().
removeIdRange()
void MultiAffineFunction::removeIdRange (unsigned idStart, unsigned idLimit) override virtual
Remove the specified range of ids.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 96 of file PWMAFunction.cpp.
References mlir::IntegerPolyhedron::removeIdRange().
swapId()
void MultiAffineFunction::swapId (unsigned posA, unsigned posB) override virtual
Swap the posA^th identifier with the posB^th identifier.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 91 of file PWMAFunction.cpp.
References mlir::IntegerPolyhedron::swapId().
valueAt()
Optional< SmallVector< int64_t, 8 > > MultiAffineFunction::valueAt (ArrayRef< int64_t > point) const
Get the value of the function at the specified point.
If the point lies outside the domain, an empty optional is returned.
Note: domains with local ids are not yet supported, and will assert-fail.
Definition at line 37 of file PWMAFunction.cpp.
References mlir::PresburgerSet::containsPoint(), mlir::PWMAFunction::getDomain(), mlir::PresburgerSpace::getNumIds(), and mlir::PWMAFunction::getNumOutputs().
Referenced by mlir::PWMAFunction::getPiece().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PWMAFunction.h
lib/Analysis/Presburger/PWMAFunction.cpp