MLIR: mlir::PresburgerSpace Class Reference
mlir::PresburgerSpace Class Reference
PresburgerSpace is a tuple of identifiers with information about what kind they correspond to.
#include "mlir/Analysis/Presburger/PresburgerSpace.h"
Public Types
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
Public Member Functions
PresburgerSpace (unsigned numDims, unsigned numSymbols)
virtual ~PresburgerSpace ()=default
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
virtual void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit).
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Detailed Description
PresburgerSpace is a tuple of identifiers with information about what kind they correspond to.
The identifiers can be split into three types:
Dimension: Ordinary variables over which the space is represented.
Symbol: Symbol identifiers correspond to fixed but unknown values. Mathematically, a space with symbolic identifiers is like a family of spaces indexed by the symbolic identifiers.
Local: Local identifiers correspond to existentially quantified variables.
PresburgerSpace only supports identifiers of kind Dimension and Symbol.
Definition at line 35 of file PresburgerSpace.h.
Member Enumeration Documentation
IdKind
enum mlir::PresburgerSpace::IdKind
Kind of identifier (column).
Enumerator
Dimension
Symbol
Local
Definition at line 40 of file PresburgerSpace.h.
Constructor & Destructor Documentation
PresburgerSpace()
mlir::PresburgerSpace::PresburgerSpace (unsigned numDims, unsigned numSymbols) inline
Definition at line 42 of file PresburgerSpace.h.
References ~PresburgerSpace().
~PresburgerSpace()
virtual mlir::PresburgerSpace::~PresburgerSpace () virtual default
Referenced by PresburgerSpace().
Member Function Documentation
getIdKindEnd()
unsigned PresburgerSpace::getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
Definition at line 35 of file PresburgerSpace.cpp.
Referenced by mlir::FlatAffineValueConstraints::computeAlignedMap().
getIdKindOffset()
unsigned PresburgerSpace::getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
Definition at line 25 of file PresburgerSpace.cpp.
Referenced by mlir::FlatAffineValueConstraints::computeAlignedMap().
getIdKindOverlap()
unsigned PresburgerSpace::getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
Definition at line 39 of file PresburgerSpace.cpp.
Referenced by removeIdRange(), and mlir::PresburgerLocalSpace::removeIdRange().
getNumDimAndSymbolIds()
unsigned mlir::PresburgerSpace::getNumDimAndSymbolIds () const inline
Definition at line 50 of file PresburgerSpace.h.
References getNumIdKind().
Referenced by mlir::FlatAffineConstraints::addBound(), mlir::computeSliceUnion(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), createFullTiles(), createSeparationCondition(), detectAsMod(), mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::getComputationSliceState(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::MultiAffineFunction::getNumInputs(), mlir::getRelationFromMap(), mlir::FlatAffineConstraints::getSliceBounds(), mergeAndAlignIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), setDimSymbolSeparation(), and turnSymbolIntoDim().
getNumDimIds()
unsigned mlir::PresburgerSpace::getNumDimIds () const inline
Definition at line 48 of file PresburgerSpace.h.
Referenced by mlir::FlatAffineConstraints::addBound(), mlir::FlatAffineValueConstraints::addDomainFromSliceMaps(), addLoopRangeConstraints(), addMissingLoopIVBounds(), addOrderingConstraints(), mlir::IntegerPolyhedron::append(), mlir::FlatAffineValueConstraints::appendDimId(), mlir::FlatAffineRelation::appendRangeId(), areIdsAligned(), assertDimensionsCompatible(), mlir::PresburgerSet::coalesce(), mlir::PresburgerSet::complement(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::FlatAffineValueConstraints::computeAlignedMap(), computeDirectionVector(), computeLocalVars(), mlir::computeSliceUnion(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), detectAsMod(), findEqualityToConstant(), generateCopy(), mlir::MemRefAccess::getAccessRelation(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::PWMAFunction::getDomain(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeDimValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), getNumCommonLoops(), mlir::getRelationFromMap(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::linalg::getUpperBoundForIndex(), mlir::MultiAffineFunction::hasCompatibleDimensions(), mlir::PWMAFunction::hasCompatibleDimensions(), mlir::PresburgerSet::intersect(), mlir::ComputationSliceState::isMaximal(), mergeAndAlignIds(), mlir::IntegerPolyhedron::mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), mlir::FlatAffineRelation::removeIdRange(), mlir::PresburgerSet::subtract(), subtractRecursively(), turnSymbolIntoDim(), mlir::IntegerPolyhedron::unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
getNumIdKind()
unsigned PresburgerSpace::getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
Definition at line 15 of file PresburgerSpace.cpp.
Referenced by getNumDimAndSymbolIds().
getNumIds()
unsigned mlir::PresburgerSpace::getNumIds () const inline
Definition at line 47 of file PresburgerSpace.h.
Referenced by mlir::LinearTransform::applyTo(), areIdsAligned(), areIdsUnique(), canonicalizeMinMaxOp(), checkExplicitRepresentation(), mlir::FlatAffineValueConstraints::clearAndCopyFrom(), computeDirectionVector(), mlir::presburger_utils::computeSingleVarRepr(), detectAsFloorDiv(), detectAsMod(), eqInvolvesSuffixDims(), findEqualityToConstant(), mlir::IntegerPolyhedron::findIntegerSample(), mlir::FlatAffineValueConstraints::FlatAffineValueConstraints(), mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), generateCopy(), mlir::FlatAffineValueConstraints::getAllValues(), mlir::FlatAffineConstraints::getAsIntegerSet(), getBestIdToEliminate(), getDivRepr(), getIndependentConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::IntegerPolyhedron::getNumCols(), mlir::PWMAFunction::getNumInputs(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::FlatAffineValueConstraints::getValues(), mlir::FlatAffineValueConstraints::hasConsistentState(), ineqInvolvesSuffixDims(), mlir::IntegerPolyhedron::IntegerPolyhedron(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::MultiAffineFunction::isConsistent(), mlir::IntegerPolyhedron::isEmpty(), mlir::ComputationSliceState::isSliceValid(), mlir::normalizeMemRefType(), mlir::FlatAffineConstraints::printSpace(), removeIdRange(), mlir::PresburgerLocalSpace::removeIdRange(), mlir::FlatAffineValueConstraints::setValue(), mlir::FlatAffineValueConstraints::setValues(), and mlir::MultiAffineFunction::valueAt().
getNumSymbolIds()
unsigned mlir::PresburgerSpace::getNumSymbolIds () const inline
Definition at line 49 of file PresburgerSpace.h.
Referenced by mlir::FlatAffineConstraints::addBound(), addLoopRangeConstraints(), mlir::IntegerPolyhedron::append(), mlir::FlatAffineValueConstraints::appendSymbolId(), areIdsAligned(), assertDimensionsCompatible(), mlir::PresburgerSet::coalesce(), mlir::PresburgerSet::complement(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::FlatAffineValueConstraints::computeAlignedMap(), computeLocalVars(), mlir::PresburgerSet::computeVolume(), detectAsMod(), generateCopy(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::PWMAFunction::getDomain(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::MultiAffineFunction::hasCompatibleDimensions(), mlir::PWMAFunction::hasCompatibleDimensions(), mlir::PresburgerSet::intersect(), mlir::ComputationSliceState::isSliceValid(), mlir::IntegerPolyhedron::mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), mlir::PresburgerSet::subtract(), subtractRecursively(), and turnSymbolIntoDim().
insertId()
unsigned PresburgerSpace::insertId (IdKind kind, unsigned pos, unsigned num = 1) virtual
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Reimplemented in mlir::FlatAffineValueConstraints, mlir::IntegerPolyhedron, mlir::PresburgerLocalSpace, and mlir::MultiAffineFunction.
Definition at line 54 of file PresburgerSpace.cpp.
Referenced by mlir::PresburgerLocalSpace::getNumLocalIds().
removeIdRange()
void PresburgerSpace::removeIdRange (unsigned idStart, unsigned idLimit) virtual
Removes identifiers in the column range [idStart, idLimit).
Reimplemented in mlir::FlatAffineRelation, mlir::FlatAffineValueConstraints, mlir::IntegerPolyhedron, mlir::PresburgerLocalSpace, and mlir::MultiAffineFunction.
Definition at line 70 of file PresburgerSpace.cpp.
References getIdKindOverlap(), and getNumIds().
Referenced by mlir::PresburgerLocalSpace::removeIdRange().
setDimSymbolSeparation()
void PresburgerSpace::setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Depending on the new symbol count, either a chunk of dimensional identifiers immediately before the split become symbols, or some of the symbols immediately after the split become dimensions.
Definition at line 118 of file PresburgerSpace.cpp.
References getNumDimAndSymbolIds().
Referenced by createFullTiles(), createSeparationCondition(), and turnSymbolIntoDim().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerSpace.h
lib/Analysis/Presburger/PresburgerSpace.cpp