MLIR: mlir::PWMAFunction Class Reference
mlir::PWMAFunction Class Reference
This class represents a piece-wise MultiAffineFunction.
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
PWMAFunction (unsigned numDims, unsigned numSymbols, unsigned numOutputs)
void addPiece (const MultiAffineFunction &piece)
void addPiece (const IntegerPolyhedron &domain, const Matrix &output)
const MultiAffineFunction & getPiece (unsigned i) const
unsigned getNumPieces () const
unsigned getNumOutputs () const
unsigned getNumInputs () const
MultiAffineFunction & getPiece (unsigned i)
PresburgerSet getDomain () const
Return the domain of this piece-wise MultiAffineFunction.
bool hasCompatibleDimensions (const MultiAffineFunction &f) const
Check whether the this and the given function have compatible dimensions, i.e., the same number of dimension inputs, symbol inputs, and outputs.
bool hasCompatibleDimensions (const PWMAFunction &f) const
Optional< SmallVector< int64_t, 8 > > valueAt (ArrayRef< int64_t > point) const
Return the value at the specified point and an empty optional if the point does not lie in the domain.
bool isEqual (const PWMAFunction &other) const
Return whether this and other are equal as PWMAFunctions, i.e.
void print (raw_ostream &os) const
void dump () const
Detailed Description
This class represents a piece-wise MultiAffineFunction.
This can be thought of as a list of MultiAffineFunction with disjoint domains, with each having their own affine expressions for their output tuples. For example, we could have a function with two input variables (x, y), defined as
f(x, y) = (2*x + y, y - 4) if x >= 0, y >= 0 = (-2*x + y, y + 4) if x < 0, y < 0 = (4, 1) if x < 0, y >= 0
Note that the domains all have to be disjoint. Otherwise, the behaviour of this class is undefined. The domains need not cover all possible points; this represents a partial function and so could be undefined at some points.
As in PresburgerSets, the input ids are partitioned into dimension ids and symbolic ids.
Support is provided to compare equality of two such functions as well as finding the value of the function at a point. Note that local ids in the piece are not supported for the latter.
Definition at line 141 of file PWMAFunction.h.
Constructor & Destructor Documentation
PWMAFunction()
mlir::PWMAFunction::PWMAFunction (unsigned numDims, unsigned numSymbols, unsigned numOutputs) inline
Definition at line 143 of file PWMAFunction.h.
Member Function Documentation
addPiece() [1/2]
void PWMAFunction::addPiece (const MultiAffineFunction & piece)
Definition at line 159 of file PWMAFunction.cpp.
References mlir::MultiAffineFunction::getDomain(), getDomain(), hasCompatibleDimensions(), mlir::MultiAffineFunction::isConsistent(), and mlir::PresburgerSet::isIntegerEmpty().
Referenced by addPiece().
addPiece() [2/2]
void PWMAFunction::addPiece (const IntegerPolyhedron & domain, const Matrix & output)
Definition at line 170 of file PWMAFunction.cpp.
References addPiece().
dump()
void mlir::PWMAFunction::dump () const
getDomain()
PresburgerSet PWMAFunction::getDomain () const
Return the domain of this piece-wise MultiAffineFunction.
This is the union of the domains of all the pieces.
Definition at line 28 of file PWMAFunction.cpp.
References mlir::PresburgerSet::getEmptySet(), mlir::PresburgerSpace::getNumDimIds(), mlir::PresburgerSpace::getNumSymbolIds(), and mlir::PresburgerSet::unionPolyInPlace().
Referenced by addPiece(), mlir::MultiAffineFunction::isEqual(), isEqual(), and mlir::MultiAffineFunction::valueAt().
getNumInputs()
unsigned mlir::PWMAFunction::getNumInputs () const inline
Definition at line 154 of file PWMAFunction.h.
References mlir::PresburgerSpace::getNumIds().
Referenced by valueAt().
getNumOutputs()
unsigned mlir::PWMAFunction::getNumOutputs () const inline
Definition at line 153 of file PWMAFunction.h.
Referenced by mlir::MultiAffineFunction::hasCompatibleDimensions(), hasCompatibleDimensions(), mlir::MultiAffineFunction::isEqualWhereDomainsOverlap(), and mlir::MultiAffineFunction::valueAt().
getNumPieces()
unsigned mlir::PWMAFunction::getNumPieces () const inline
Definition at line 152 of file PWMAFunction.h.
getPiece() [1/2]
const MultiAffineFunction& mlir::PWMAFunction::getPiece (unsigned i) const inline
Definition at line 151 of file PWMAFunction.h.
getPiece() [2/2]
MultiAffineFunction& mlir::PWMAFunction::getPiece (unsigned i) inline
Definition at line 155 of file PWMAFunction.h.
References mlir::MultiAffineFunction::dump(), mlir::MultiAffineFunction::getDomain(), mlir::MultiAffineFunction::hasCompatibleDimensions(), mlir::MultiAffineFunction::isEqual(), mlir::MultiAffineFunction::print(), and mlir::MultiAffineFunction::valueAt().
hasCompatibleDimensions() [1/2]
bool PWMAFunction::hasCompatibleDimensions (const MultiAffineFunction & f) const
Check whether the this and the given function have compatible dimensions, i.e., the same number of dimension inputs, symbol inputs, and outputs.
Definition at line 189 of file PWMAFunction.cpp.
References mlir::PresburgerSpace::getNumDimIds(), mlir::MultiAffineFunction::getNumOutputs(), getNumOutputs(), and mlir::PresburgerSpace::getNumSymbolIds().
Referenced by addPiece(), mlir::MultiAffineFunction::isEqual(), isEqual(), and mlir::MultiAffineFunction::isEqualWhereDomainsOverlap().
hasCompatibleDimensions() [2/2]
bool PWMAFunction::hasCompatibleDimensions (const PWMAFunction & f) const
Definition at line 194 of file PWMAFunction.cpp.
References mlir::PresburgerSpace::getNumDimIds(), getNumOutputs(), and mlir::PresburgerSpace::getNumSymbolIds().
isEqual()
bool PWMAFunction::isEqual (const PWMAFunction & other) const
Return whether this and other are equal as PWMAFunctions, i.e.
Two PWMAFunctions are equal if they have the same dimensionalities, the same domain, and take the same value at every point in the domain.
whether they have the same dimensions, the same domain and they take the same value at every point in the domain.
Definition at line 141 of file PWMAFunction.cpp.
References getDomain(), and hasCompatibleDimensions().
print()
void PWMAFunction::print (raw_ostream & os) const
Definition at line 175 of file PWMAFunction.cpp.
Referenced by mlir::MultiAffineFunction::dump().
valueAt()
Optional< SmallVector< int64_t, 8 > > PWMAFunction::valueAt (ArrayRef< int64_t > point) const
Return the value at the specified point and an empty optional if the point does not lie in the domain.
Note: domains with local ids are not yet supported, and will assert-fail.
Definition at line 59 of file PWMAFunction.cpp.
References getNumInputs().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PWMAFunction.h
lib/Analysis/Presburger/PWMAFunction.cpp