MLIR: mlir::PresburgerLocalSpace Class Reference
mlir::PresburgerLocalSpace Class Reference
Extension of PresburgerSpace supporting Local identifiers.
#include "mlir/Analysis/Presburger/PresburgerSpace.h"
Public Member Functions
PresburgerLocalSpace (unsigned numDims, unsigned numSymbols, unsigned numLocals)
unsigned getNumLocalIds () const
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1) override
Insert num identifiers of the specified kind at position pos.
void removeIdRange (unsigned idStart, unsigned idLimit) override
Removes identifiers in the column range [idStart, idLimit).
Public Member Functions inherited from mlir::PresburgerSpace
PresburgerSpace (unsigned numDims, unsigned numSymbols)
virtual ~PresburgerSpace ()=default
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Additional Inherited Members
Public Types inherited from mlir::PresburgerSpace
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
Detailed Description
Extension of PresburgerSpace supporting Local identifiers.
Definition at line 97 of file PresburgerSpace.h.
Constructor & Destructor Documentation
PresburgerLocalSpace()
mlir::PresburgerLocalSpace::PresburgerLocalSpace (unsigned numDims, unsigned numSymbols, unsigned numLocals) inline
Definition at line 99 of file PresburgerSpace.h.
Member Function Documentation
getNumLocalIds()
unsigned mlir::PresburgerLocalSpace::getNumLocalIds () const inline
Definition at line 103 of file PresburgerSpace.h.
References mlir::PresburgerSpace::insertId().
Referenced by computeLocalVars(), mlir::computeSliceUnion(), mlir::FlatAffineConstraints::FlatAffineConstraints(), mlir::FlatAffineConstraints::flattenAlignedMapAndMergeLocals(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), mlir::IntegerPolyhedron::mergeLocalIds(), mlir::normalizeMemRefType(), subtractRecursively(), mlir::IntegerPolyhedron::unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
insertId()
unsigned PresburgerLocalSpace::insertId (IdKind kind, unsigned pos, unsigned num = 1) override virtual
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Reimplemented from mlir::PresburgerSpace.
Reimplemented in mlir::FlatAffineValueConstraints, and mlir::MultiAffineFunction.
Definition at line 89 of file PresburgerSpace.cpp.
removeIdRange()
void PresburgerLocalSpace::removeIdRange (unsigned idStart, unsigned idLimit) override virtual
Removes identifiers in the column range [idStart, idLimit).
Reimplemented from mlir::PresburgerSpace.
Reimplemented in mlir::FlatAffineRelation, mlir::FlatAffineValueConstraints, and mlir::MultiAffineFunction.
Definition at line 98 of file PresburgerSpace.cpp.
References mlir::PresburgerSpace::getIdKindOverlap(), mlir::PresburgerSpace::getNumIds(), min(), and mlir::PresburgerSpace::removeIdRange().
Referenced by mlir::IntegerPolyhedron::removeIdRange().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerSpace.h
lib/Analysis/Presburger/PresburgerSpace.cpp