MLIR: mlir::PresburgerSet Class Reference
mlir::PresburgerSet Class Reference
This class can represent a union of IntegerPolyhedrons, with support for union, intersection, subtraction and complement operations, as well as sampling.
#include "mlir/Analysis/Presburger/PresburgerSet.h"
Public Member Functions
PresburgerSet (const IntegerPolyhedron &poly)
unsigned getNumPolys () const
Return the number of Polys in the union.
ArrayRef< IntegerPolyhedron > getAllIntegerPolyhedron () const
Return a reference to the list of IntegerPolyhedrons.
const IntegerPolyhedron & getIntegerPolyhedron (unsigned index) const
Return the IntegerPolyhedron at the specified index.
void unionPolyInPlace (const IntegerPolyhedron &poly)
Mutate this set, turning it into the union of this set and the given IntegerPolyhedron.
void unionSetInPlace (const PresburgerSet &set)
Mutate this set, turning it into the union of this set and the given set.
PresburgerSet unionSet (const PresburgerSet &set) const
Return the union of this set and the given set.
PresburgerSet intersect (const PresburgerSet &set) const
Return the intersection of this set and the given set.
bool containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
void print (raw_ostream &os) const
Print the set's internal state.
void dump () const
PresburgerSet complement () const
Return the complement of this set.
PresburgerSet subtract (const PresburgerSet &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
bool isSubsetOf (const PresburgerSet &set) const
Return true if this set is a subset of the given set, and false otherwise.
bool isEqual (const PresburgerSet &set) const
Return true if this set is equal to the given set, and false otherwise.
bool isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
bool findIntegerSample (SmallVectorImpl< int64_t > &sample)
Find an integer sample from the given set.
Optional< uint64_t > computeVolume () const
Compute an overapproximation of the number of integer points in the polyhedron.
PresburgerSet coalesce () const
Simplifies the representation of a PresburgerSet.
Public Member Functions inherited from mlir::PresburgerSpace
PresburgerSpace (unsigned numDims, unsigned numSymbols)
virtual ~PresburgerSpace ()=default
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getIdKindEnd (IdKind kind) const
Return the index at Which the specified kind of id ends.
unsigned getIdKindOverlap (IdKind kind, unsigned idStart, unsigned idLimit) const
Get the number of elements of the specified kind in the range [idStart, idLimit).
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
virtual void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit).
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Static Public Member Functions
static PresburgerSet getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a universe set of the specified type that contains all points.
static PresburgerSet getEmptySet (unsigned numDims=0, unsigned numSymbols=0)
Return an empty set of the specified type that contains no points.
Additional Inherited Members
Public Types inherited from mlir::PresburgerSpace
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
Detailed Description
This class can represent a union of IntegerPolyhedrons, with support for union, intersection, subtraction and complement operations, as well as sampling.
The IntegerPolyhedrons (Polys) are stored in a vector, and the set represents the union of these Polys. An empty list corresponds to the empty set.
Note that there are no invariants guaranteed on the list of Poly other than that they are all in the same space, i.e., they all have the same number of dimensions and symbols. For example, the Polys may overlap each other.
Definition at line 31 of file PresburgerSet.h.
Constructor & Destructor Documentation
PresburgerSet()
PresburgerSet::PresburgerSet (const IntegerPolyhedron & poly) explicit
Definition at line 18 of file PresburgerSet.cpp.
References unionPolyInPlace().
Referenced by getEmptySet().
Member Function Documentation
coalesce()
PresburgerSet PresburgerSet::coalesce () const
Simplifies the representation of a PresburgerSet.
In particular, removes all Polys which are subsets of other Polys in the union.
Definition at line 398 of file PresburgerSet.cpp.
References getEmptySet(), mlir::PresburgerSpace::getNumDimIds(), getNumPolys(), mlir::PresburgerSpace::getNumSymbolIds(), mlir::SimplexBase::isEmpty(), mlir::Simplex::isRationalSubsetOf(), and unionPolyInPlace().
complement()
PresburgerSet PresburgerSet::complement () const
Return the complement of this set.
All local variables in the set must correspond to floor divisions.
Definition at line 335 of file PresburgerSet.cpp.
References mlir::PresburgerSpace::getNumDimIds(), mlir::PresburgerSpace::getNumSymbolIds(), and mlir::IntegerPolyhedron::getUniverse().
computeVolume()
Optional< uint64_t > PresburgerSet::computeVolume () const
Compute an overapproximation of the number of integer points in the polyhedron.
Symbol ids are currently not supported. If the computed overapproximation is infinite, an empty optional is returned.
This currently just sums up the overapproximations of the volumes of the disjuncts, so the approximation might be far from the true volume in the case when there is a lot of overlap between disjuncts.
Definition at line 384 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::computeVolume(), and mlir::PresburgerSpace::getNumSymbolIds().
containsPoint()
bool PresburgerSet::containsPoint (ArrayRef< int64_t > point) const
Return true if the set contains the given point, and false otherwise.
A point is contained in the union iff any of the parts contain the point.
Definition at line 84 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::containsPoint().
Referenced by mlir::MultiAffineFunction::valueAt().
dump()
void PresburgerSet::dump () const
Definition at line 443 of file PresburgerSet.cpp.
References print().
findIntegerSample()
bool PresburgerSet::findIntegerSample (SmallVectorImpl< int64_t > & sample)
Find an integer sample from the given set.
This should not be called if any of the Polys in the union are unbounded.
Definition at line 373 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::findIntegerSample().
getAllIntegerPolyhedron()
ArrayRef< IntegerPolyhedron > PresburgerSet::getAllIntegerPolyhedron () const
Return a reference to the list of IntegerPolyhedrons.
Definition at line 27 of file PresburgerSet.cpp.
getEmptySet()
PresburgerSet PresburgerSet::getEmptySet (unsigned numDims = 0, unsigned numSymbols = 0) static
Return an empty set of the specified type that contains no points.
Definition at line 97 of file PresburgerSet.cpp.
References PresburgerSet().
Referenced by coalesce(), mlir::PWMAFunction::getDomain(), and subtractRecursively().
getIntegerPolyhedron()
const IntegerPolyhedron & PresburgerSet::getIntegerPolyhedron (unsigned index) const
Return the IntegerPolyhedron at the specified index.
Definition at line 32 of file PresburgerSet.cpp.
Referenced by subtractRecursively().
getNumPolys()
unsigned PresburgerSet::getNumPolys () const
Return the number of Polys in the union.
Definition at line 23 of file PresburgerSet.cpp.
Referenced by coalesce(), print(), and subtractRecursively().
getUniverse()
PresburgerSet PresburgerSet::getUniverse (unsigned numDims = 0, unsigned numSymbols = 0) static
Return a universe set of the specified type that contains all points.
Definition at line 90 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::getUniverse(), and unionPolyInPlace().
intersect()
PresburgerSet PresburgerSet::intersect (const PresburgerSet & set) const
Return the intersection of this set and the given set.
Definition at line 109 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::append(), assertDimensionsCompatible(), mlir::PresburgerSpace::getNumDimIds(), mlir::PresburgerSpace::getNumSymbolIds(), mlir::IntegerPolyhedron::isEmpty(), mlir::IntegerPolyhedron::mergeLocalIds(), and unionPolyInPlace().
isEqual()
bool PresburgerSet::isEqual (const PresburgerSet & set) const
Return true if this set is equal to the given set, and false otherwise.
Two sets are equal iff they are subsets of each other.
All local variables in both sets must correspond to floor divisions.
Definition at line 359 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and isSubsetOf().
Referenced by mlir::MultiAffineFunction::isEqual(), and mlir::IntegerPolyhedron::isEqual().
isIntegerEmpty()
bool PresburgerSet::isIntegerEmpty () const
Return true if all the sets in the union are known to be integer empty false otherwise.
Return true if all the sets in the union are known to be integer empty, false otherwise.
Definition at line 366 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::isIntegerEmpty().
Referenced by mlir::PWMAFunction::addPiece(), mlir::ComputationSliceState::isMaximal(), mlir::ComputationSliceState::isSliceValid(), and isSubsetOf().
isSubsetOf()
bool PresburgerSet::isSubsetOf (const PresburgerSet & set) const
Return true if this set is a subset of the given set, and false otherwise.
T is a subset of S iff T \ S is empty, since if T \ S contains a point then this is a point that is contained in T but not S, and if T contains a point that is not in S, this also lies in T \ S.
Definition at line 354 of file PresburgerSet.cpp.
References isIntegerEmpty(), and subtract().
Referenced by isEqual(), and mlir::IntegerPolyhedron::isSubsetOf().
print()
void PresburgerSet::print (raw_ostream & os) const
Print the set's internal state.
Definition at line 435 of file PresburgerSet.cpp.
References getNumPolys(), and mlir::IntegerPolyhedron::print().
Referenced by dump().
subtract()
PresburgerSet PresburgerSet::subtract (const PresburgerSet & set) const
Return the set difference of this set and the given set, i.e., return this \ set.
Return the result of subtract the given set from this set, i.e., return this \ set.
All local variables in set must correspond to floor divisions, but local variables in this need not correspond to divisions.
Definition at line 342 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), mlir::PresburgerSpace::getNumDimIds(), mlir::PresburgerSpace::getNumSymbolIds(), and unionSetInPlace().
Referenced by mlir::ComputationSliceState::isMaximal(), mlir::ComputationSliceState::isSliceValid(), and isSubsetOf().
unionPolyInPlace()
void PresburgerSet::unionPolyInPlace (const IntegerPolyhedron & poly)
Mutate this set, turning it into the union of this set and the given IntegerPolyhedron.
Definition at line 60 of file PresburgerSet.cpp.
References assertDimensionsCompatible().
Referenced by coalesce(), mlir::PWMAFunction::getDomain(), getUniverse(), intersect(), PresburgerSet(), subtractRecursively(), and unionSetInPlace().
unionSet()
PresburgerSet PresburgerSet::unionSet (const PresburgerSet & set) const
Return the union of this set and the given set.
Definition at line 76 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and unionSetInPlace().
unionSetInPlace()
void PresburgerSet::unionSetInPlace (const PresburgerSet & set)
Mutate this set, turning it into the union of this set and the given set.
This is accomplished by simply adding all the Poly of the given set to this set.
Definition at line 69 of file PresburgerSet.cpp.
References assertDimensionsCompatible(), and unionPolyInPlace().
Referenced by subtract(), and unionSet().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PresburgerSet.h
lib/Analysis/Presburger/PresburgerSet.cpp