MLIR: mlir::SimplexBase Class Reference
mlir::SimplexBase Class Reference abstract
The Simplex class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
#include "mlir/Analysis/Presburger/Simplex.h"
Classes
struct Pivot
struct Unknown
An Unknown is either a variable or a constraint.
Public Member Functions
SimplexBase ()=delete
virtual ~SimplexBase ()=default
SimplexBase (unsigned nVar, bool mustUseBigM)
Construct a SimplexBase with the specified number of variables and fixed columns.
bool isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
virtual void addInequality (ArrayRef< int64_t > coeffs)=0
Add an inequality to the tableau.
unsigned getNumVariables () const
Returns the number of variables in the tableau.
unsigned getNumConstraints () const
Returns the number of constraints in the tableau.
void addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
void appendVariable (unsigned count=1)
Add new variables to the end of the list of variables.
void markEmpty ()
Mark the tableau as being empty.
unsigned getSnapshot () const
Get a snapshot of the current state.
unsigned getSnapshotBasis ()
Get a snapshot of the current state including the basis.
void rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
void intersectIntegerPolyhedron (const IntegerPolyhedron &poly)
Add all the constraints from the given IntegerPolyhedron.
Optional< SmallVector< Fraction, 8 > > getRationalSample () const
Returns the current sample point, which may contain non-integer (rational) coordinates.
void print (raw_ostream &os) const
Print the tableau's internal state.
void dump () const
Protected Types
enum Orientation { Orientation::Row, Orientation::Column }
enum UndoLogEntry {
UndoLogEntry::RemoveLastConstraint, UndoLogEntry::RemoveLastVariable, UndoLogEntry::UnmarkEmpty, UndoLogEntry::UnmarkLastRedundant,
UndoLogEntry::RestoreBasis
}
Enum to denote operations that need to be undone during rollback.
Protected Member Functions
Optional< unsigned > findAnyPivotRow (unsigned col)
Return any row that this column can be pivoted with, ignoring tableau consistency.
void swapRowWithCol (unsigned row, unsigned col)
Swap the row with the column in the tableau's data structures but not the tableau itself.
void pivot (unsigned row, unsigned col)
Pivot the row with the column.
void pivot (Pivot pair)
const Unknown & unknownFromIndex (int index) const
Returns the unknown associated with index.
const Unknown & unknownFromColumn (unsigned col) const
Returns the unknown associated with col.
const Unknown & unknownFromRow (unsigned row) const
Returns the unknown associated with row.
Unknown & unknownFromIndex (int index)
Returns the unknown associated with index.
Unknown & unknownFromColumn (unsigned col)
Returns the unknown associated with col.
Unknown & unknownFromRow (unsigned row)
Returns the unknown associated with row.
unsigned addRow (ArrayRef< int64_t > coeffs, bool makeRestricted=false)
Add a new row to the tableau and the associated data structures.
void normalizeRow (unsigned row)
Normalize the given row by removing common factors between the numerator and the denominator.
void swapRows (unsigned i, unsigned j)
Swap the two rows/columns in the tableau and associated data structures.
void swapColumns (unsigned i, unsigned j)
virtual void undoLastConstraint ()=0
Undo the addition of the last constraint.
void removeLastConstraintRowOrientation ()
Remove the last constraint, which must be in row orientation.
void undo (UndoLogEntry entry)
Undo the operation represented by the log entry.
unsigned getNumFixedCols () const
Return the number of fixed columns, as described in the constructor above, this is the number of columns beyond those for the variables in var.
Protected Attributes
const bool usingBigM
Stores whether or not a big M column is present in the tableau.
unsigned nRow
The number of rows in the tableau.
unsigned nCol
The number of columns in the tableau, including the common denominator and the constant column.
unsigned nRedundant
The number of redundant rows in the tableau.
Matrix tableau
The matrix representing the tableau.
bool empty
This is true if the tableau has been detected to be empty, false otherwise.
SmallVector< UndoLogEntry, 8 > undoLog
Holds a log of operations, used for rolling back to a previous state.
SmallVector< SmallVector< int, 8 >, 8 > savedBases
Holds a vector of bases.
SmallVector< int, 8 > rowUnknown
These hold the indexes of the unknown at a given row or column position.
SmallVector< int, 8 > colUnknown
SmallVector< Unknown, 8 > con
These hold information about each unknown.
SmallVector< Unknown, 8 > var
Detailed Description
The Simplex class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
A Simplex can be constructed by specifying the dimensionality of the set. It supports adding affine inequalities and equalities, and can perform emptiness checks, i.e., it can find a solution to the set of constraints if one exists, or say that the set is empty if no solution exists. Furthermore, it can find a subset of these constraints that are redundant, i.e. a subset of constraints that doesn't constrain the affine set further after adding the non-redundant constraints. The LexSimplex class provides support for computing the lexicographical minimum of an IntegerPolyhedron. Both these classes can be constructed from an IntegerPolyhedron, and both inherit common functionality from SimplexBase.
The implementations of the Simplex and SimplexBase classes, other than the functionality for obtaining an integer sample, are based on the paper "Simplify: A Theorem Prover for Program Checking" by D. Detlefs, G. Nelson, J. B. Saxe.
We define variables, constraints, and unknowns. Consider the example of a two-dimensional set defined by 1 + 2x + 3y >= 0 and 2x - 3y >= 0. Here, x, y, are variables while 1 + 2x + 3y >= 0, 2x - 3y >= 0 are constraints. Unknowns are either variables or constraints, i.e., x, y, 1 + 2x + 3y >= 0, 2x - 3y >= 0 are all unknowns.
The implementation involves a matrix called a tableau, which can be thought of as a 2D matrix of rational numbers having number of rows equal to the number of constraints and number of columns equal to one plus the number of variables. In our implementation, instead of storing rational numbers, we store a common denominator for each row, so it is in fact a matrix of integers with number of rows equal to number of constraints and number of columns equal to two plus the number of variables. For example, instead of storing a row of three rationals [1/2, 2/3, 3], we would store [6, 3, 4, 18] since 3/6 = 1/2, 4/6 = 2/3, and 18/6 = 3.
Every row and column except the first and second columns is associated with an unknown and every unknown is associated with a row or column. An unknown associated with a row or column is said to be in row or column orientation respectively. As described above, the first column is the common denominator. The second column represents the constant term, explained in more detail below. These two are fixed columns; they always retain their position as the first and second columns. Additionally, LexSimplex stores a so-call big M parameter (explained below) in the third column, so LexSimplex has three fixed columns.
LexSimplex does not directly support variables which can be negative, so we introduce the so-called big M parameter, an artificial variable that is considered to have an arbitrarily large value. We then transform the variables, say x, y, z, ... to M, M + x, M + y, M + z. Since M has been added to these variables, they are now known to have non-negative values. For more details, see the documentation for LexSimplex. The big M parameter is not considered a real unknown and is not stored in the var data structure; rather the tableau just has an extra fixed column for it just like the constant term.
The vectors var and con store information about the variables and constraints respectively, namely, whether they are in row or column position, which row or column they are associated with, and whether they correspond to a variable or a constraint.
An unknown is addressed by its index. If the index i is non-negative, then the variable var[i] is being addressed. If the index i is negative, then the constraint con[~i] is being addressed. Effectively this maps 0 -> var[0], 1 -> var[1], -1 -> con[0], -2 -> con[1], etc. rowUnknown[r] and colUnknown[c] are the indexes of the unknowns associated with row r and column c, respectively.
The unknowns in column position are together called the basis. Initially the basis is the set of variables – in our example above, the initial basis is x, y.
The unknowns in row position are represented in terms of the basis unknowns. If the basis unknowns are u_1, u_2, ... u_m, and a row in the tableau is d, c, a_1, a_2, ... a_m, this represents the unknown for that row as (c + a_1*u_1 + a_2*u_2 + ... + a_m*u_m)/d. In our running example, if the basis is the initial basis of x, y, then the constraint 1 + 2x + 3y >= 0 would be represented by the row [1, 1, 2, 3].
The association of unknowns to rows and columns can be changed by a process called pivoting, where a row unknown and a column unknown exchange places and the remaining row variables' representation is changed accordingly by eliminating the old column unknown in favour of the new column unknown. If we had pivoted the column for x with the row for 2x - 3y >= 0, the new row for x would be [2, 1, 3] since x = (1*(2x - 3y) + 3*y)/2. See the documentation for the pivot member function for details.
The association of unknowns to rows and columns is called the tableau configuration. The sample value of an unknown in a particular tableau configuration is its value if all the column unknowns were set to zero. Concretely, for unknowns in column position the sample value is zero; when the big M parameter is not used, for unknowns in row position the sample value is the constant term divided by the common denominator. When the big M parameter is used, if d is the denominator, p is the big M coefficient, and c is the constant term, then the sample value is (p*M + c)/d. Since M is considered to be positive infinity, this is positive (negative) infinity when p is positive or negative, and c/d when p is zero.
The tableau configuration is called consistent if the sample value of all restricted unknowns is non-negative. Initially there are no constraints, and the tableau is consistent. When a new constraint is added, its sample value in the current tableau configuration may be negative. In that case, we try to find a series of pivots to bring us to a consistent tableau configuration, i.e. we try to make the new constraint's sample value non-negative without making that of any other constraints negative. (See findPivot and findPivotRow for details.) If this is not possible, then the set of constraints is mutually contradictory and the tableau is marked empty, which means the set of constraints has no solution.
This SimplexBase class also supports taking snapshots of the current state and rolling back to prior snapshots. This works by maintaining an undo log of operations. Snapshots are just pointers to a particular location in the log, and rolling back to a snapshot is done by reverting each log entry's operation from the end until we reach the snapshot's location. SimplexBase also supports taking a snapshot including the exact set of basis unknowns; if this functionality is used, then on rolling back the exact basis will also be restored. This is used by LexSimplex because its algorithm, unlike Simplex, is sensitive to the exact basis used at a point.
Definition at line 149 of file Simplex.h.
Member Enumeration Documentation
Orientation
enum mlir::SimplexBase::Orientation strong protected
Enumerator
Row
Column
Definition at line 218 of file Simplex.h.
UndoLogEntry
enum mlir::SimplexBase::UndoLogEntry strong protected
Enum to denote operations that need to be undone during rollback.
Enumerator
RemoveLastConstraint
RemoveLastVariable
UnmarkEmpty
UnmarkLastRedundant
RestoreBasis
Definition at line 291 of file Simplex.h.
Constructor & Destructor Documentation
SimplexBase() [1/2]
mlir::SimplexBase::SimplexBase () delete
~SimplexBase()
virtual mlir::SimplexBase::~SimplexBase () virtual default
SimplexBase() [2/2]
mlir::SimplexBase::SimplexBase (unsigned nVar, bool mustUseBigM)
Construct a SimplexBase with the specified number of variables and fixed columns.
For example, Simplex uses two fixed columns: the denominator and the constant term, whereas LexSimplex has an extra fixed column for the so-called big M parameter. For more information see the documentation for LexSimplex.
Definition at line 19 of file Simplex.cpp.
References Column, colUnknown, getNumFixedCols(), mlir::nullIndex, and var.
Member Function Documentation
addEquality()
void mlir::SimplexBase::addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
We simply add two opposing inequalities, which force the expression to be zero.
Definition at line 594 of file Simplex.cpp.
References addInequality().
Referenced by mlir::Simplex::findIntegerSample(), and intersectIntegerPolyhedron().
addInequality()
virtual void mlir::SimplexBase::addInequality (ArrayRef< int64_t > coeffs) pure virtual
Add an inequality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
Implemented in mlir::Simplex, and mlir::LexSimplex.
Referenced by addEquality(), intersectIntegerPolyhedron(), and mlir::Simplex::Simplex().
addRow()
unsigned mlir::SimplexBase::addRow (ArrayRef< int64_t > coeffs, bool makeRestricted = false) protected
Add a new row to the tableau and the associated data structures.
Add a new row to the tableau corresponding to the given constant term and list of coefficients.
The new row is considered to be a constraint; the new Unknown lives in con.
Returns the index of the new Unknown in con.
The coefficients are specified as a vector of (variable index, coefficient) pairs.
Definition at line 63 of file Simplex.cpp.
References Column, con, mlir::Matrix::fillRow(), mlir::Matrix::getNumRows(), mlir::lcm(), nCol, normalizeRow(), nRow, RemoveLastConstraint, mlir::Matrix::resizeVertically(), Row, rowUnknown, tableau, undoLog, usingBigM, and var.
Referenced by mlir::LexSimplex::addInequality(), mlir::Simplex::addInequality(), and mlir::Simplex::computeOptimum().
appendVariable()
void mlir::SimplexBase::appendVariable (unsigned count = 1)
Add new variables to the end of the list of variables.
Definition at line 764 of file Simplex.cpp.
References Column, colUnknown, nCol, RemoveLastVariable, mlir::Matrix::resizeHorizontally(), tableau, undoLog, and var.
Referenced by subtractRecursively().
dump()
void mlir::SimplexBase::dump () const
Definition at line 1568 of file Simplex.cpp.
References print().
findAnyPivotRow()
Optional< unsigned > mlir::SimplexBase::findAnyPivotRow (unsigned col) protected
Return any row that this column can be pivoted with, ignoring tableau consistency.
Returns an empty optional if no pivot is possible, which happens only when the column unknown is a variable and no constraint has a non-zero coefficient for it.
Definition at line 644 of file Simplex.cpp.
References Column, con, mlir::Simplex::Down, nRedundant, nRow, pivot(), removeLastConstraintRowOrientation(), tableau, and mlir::Simplex::Up.
Referenced by mlir::LexSimplex::undoLastConstraint().
getNumConstraints()
unsigned mlir::SimplexBase::getNumConstraints () const
Returns the number of constraints in the tableau.
Definition at line 603 of file Simplex.cpp.
References con.
Referenced by mlir::Simplex::makeProduct(), and subtractRecursively().
getNumFixedCols()
unsigned mlir::SimplexBase::getNumFixedCols () const inline protected
Return the number of fixed columns, as described in the constructor above, this is the number of columns beyond those for the variables in var.
Definition at line 311 of file Simplex.h.
References usingBigM.
Referenced by pivot(), SimplexBase(), and undo().
getNumVariables()
unsigned mlir::SimplexBase::getNumVariables () const
Returns the number of variables in the tableau.
Definition at line 602 of file Simplex.cpp.
References var.
Referenced by intersectIntegerPolyhedron(), and mlir::Simplex::makeProduct().
getRationalSample()
Optional< SmallVector< Fraction, 8 > > mlir::SimplexBase::getRationalSample () const
Returns the current sample point, which may contain non-integer (rational) coordinates.
Returns an empty optional when the tableau is empty.
Also returns empty when the big M parameter is used and a variable has a non-zero big M coefficient, meaning its value is infinite or unbounded.
Definition at line 1013 of file Simplex.cpp.
References Column, empty, mlir::SimplexBase::Unknown::orientation, mlir::SimplexBase::Unknown::pos, tableau, usingBigM, and var.
Referenced by mlir::IntegerPolyhedron::findIntegerSample(), mlir::LexSimplex::getRationalLexMin(), and mlir::Simplex::getSamplePointIfIntegral().
getSnapshot()
unsigned mlir::SimplexBase::getSnapshot () const
Get a snapshot of the current state.
Return a snapshot of the current state.
This is used for rolling back. The same basis will not necessarily be restored on rolling back. The snapshot only captures the set of variables and constraints present in the Simplex.
This is just the current size of the undo log.
Definition at line 607 of file Simplex.cpp.
References undoLog.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::findIntegerSample(), and subtractRecursively().
getSnapshotBasis()
unsigned mlir::SimplexBase::getSnapshotBasis ()
Get a snapshot of the current state including the basis.
When rolling back, the exact basis will be restored.
Definition at line 609 of file Simplex.cpp.
References colUnknown, RestoreBasis, savedBases, and undoLog.
Referenced by mlir::LexSimplex::getSnapshot().
intersectIntegerPolyhedron()
void mlir::SimplexBase::intersectIntegerPolyhedron (const IntegerPolyhedron & poly)
Add all the constraints from the given IntegerPolyhedron.
Definition at line 780 of file Simplex.cpp.
References addEquality(), addInequality(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::PresburgerSpace::getNumIds(), mlir::IntegerPolyhedron::getNumInequalities(), and getNumVariables().
Referenced by mlir::LexSimplex::LexSimplex(), mlir::Simplex::Simplex(), and subtractRecursively().
isEmpty()
bool mlir::SimplexBase::isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
Definition at line 542 of file Simplex.cpp.
References empty.
Referenced by mlir::PresburgerSet::coalesce(), mlir::IntegerPolyhedron::computeVolume(), mlir::IntegerPolyhedron::findIntegerSample(), mlir::IntegerPolyhedron::getBoundedDirections(), mlir::Simplex::isRationalSubsetOf(), and subtractRecursively().
markEmpty()
void mlir::SimplexBase::markEmpty ()
Mark the tableau as being empty.
Mark this tableau empty and push an entry to the undo stack.
Definition at line 564 of file Simplex.cpp.
References empty, undoLog, and UnmarkEmpty.
Referenced by mlir::Simplex::addInequality(), and mlir::LexSimplex::moveRowUnknownToColumn().
normalizeRow()
void mlir::SimplexBase::normalizeRow (unsigned row) protected
Normalize the given row by removing common factors between the numerator and the denominator.
Normalize the row by removing factors that are common between the denominator and all the numerator coefficients.
Definition at line 133 of file Simplex.cpp.
References mlir::Simplex::Down, nCol, tableau, and mlir::Simplex::Up.
Referenced by addRow(), and pivot().
pivot() [1/2]
void mlir::SimplexBase::pivot (unsigned pivotRow, unsigned pivotCol) protected
Pivot the row with the column.
Pivot pivotRow and pivotCol.
Let R be the pivot row unknown and let C be the pivot col unknown. Since initially R = a*C + sum b_i * X_i (where the sum is over the other column's unknowns, x_i) C = (R - (sum b_i * X_i))/a
Let u be some other row unknown. u = c*C + sum d_i * X_i So u = c*(R - sum b_i * X_i)/a + sum d_i * X_i
This results in the following transform: pivot col other col pivot col other col pivot row a b -> pivot row 1/a -b/a other row c d other row c/a d - bc/a
Taking into account the common denominators p and q:
       pivot col    other col                    pivot col   other col
pivot row a/p b/p -> pivot row p/a -b/a other row c/q d/q other row cp/aq (da - bc)/aq
The pivot row transform is accomplished be swapping a with the pivot row's common denominator and negating the pivot row except for the pivot column element.
Definition at line 424 of file Simplex.cpp.
References Column, getNumFixedCols(), nCol, normalizeRow(), nRedundant, nRow, mlir::SimplexBase::Unknown::orientation, mlir::SimplexBase::Unknown::pos, Row, rowUnknown, mlir::success(), swapRowWithCol(), tableau, unknownFromRow(), and mlir::Simplex::Up.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::computeRowOptimum(), mlir::Simplex::detectRedundant(), findAnyPivotRow(), mlir::LexSimplex::moveRowUnknownToColumn(), pivot(), undo(), and mlir::LexSimplex::undoLastConstraint().
pivot() [2/2]
void mlir::SimplexBase::pivot (Pivot pair) protected
Definition at line 397 of file Simplex.cpp.
References mlir::SimplexBase::Pivot::column, pivot(), and mlir::SimplexBase::Pivot::row.
print()
void mlir::SimplexBase::print (raw_ostream & os) const
Print the tableau's internal state.
Definition at line 1533 of file Simplex.cpp.
References colUnknown, con, empty, nCol, nRow, rowUnknown, tableau, and var.
Referenced by dump().
removeLastConstraintRowOrientation()
void mlir::SimplexBase::removeLastConstraintRowOrientation () protected
Remove the last constraint, which must be in row orientation.
Definition at line 621 of file Simplex.cpp.
References con, nRow, mlir::Matrix::resizeVertically(), Row, rowUnknown, swapRows(), and tableau.
Referenced by findAnyPivotRow(), and mlir::LexSimplex::undoLastConstraint().
rollback()
void mlir::SimplexBase::rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
Rollback to the specified snapshot.
We undo all the log entries until the log size when the snapshot was taken is reached.
Definition at line 757 of file Simplex.cpp.
References undo(), and undoLog.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::findIntegerSample(), and subtractRecursively().
swapColumns()
void mlir::SimplexBase::swapColumns (unsigned i, unsigned j) protected
Definition at line 553 of file Simplex.cpp.
References colUnknown, nCol, mlir::SimplexBase::Unknown::pos, mlir::Matrix::swapColumns(), tableau, and unknownFromColumn().
Referenced by undo().
swapRows()
void mlir::SimplexBase::swapRows (unsigned i, unsigned j) protected
Swap the two rows/columns in the tableau and associated data structures.
Definition at line 544 of file Simplex.cpp.
References mlir::SimplexBase::Unknown::pos, rowUnknown, mlir::Matrix::swapRows(), tableau, and unknownFromRow().
Referenced by mlir::Simplex::isMarkedRedundant(), and removeLastConstraintRowOrientation().
swapRowWithCol()
void mlir::SimplexBase::swapRowWithCol (unsigned row, unsigned col) protected
Swap the row with the column in the tableau's data structures but not the tableau itself.
Swap the associated unknowns for the row and the column.
This is used by pivot.
First we swap the index associated with the row and column. Then we update the unknowns to reflect their new position and orientation.
Definition at line 387 of file Simplex.cpp.
References Column, colUnknown, mlir::SimplexBase::Unknown::orientation, mlir::SimplexBase::Unknown::pos, Row, rowUnknown, unknownFromColumn(), and unknownFromRow().
Referenced by pivot().
undo()
void mlir::SimplexBase::undo (UndoLogEntry entry) protected
Undo the operation represented by the log entry.
Definition at line 697 of file Simplex.cpp.
References Column, colUnknown, empty, getNumFixedCols(), nCol, nRedundant, mlir::SimplexBase::Unknown::orientation, pivot(), mlir::SimplexBase::Unknown::pos, RemoveLastConstraint, RemoveLastVariable, mlir::Matrix::resizeHorizontally(), RestoreBasis, savedBases, swapColumns(), tableau, undoLastConstraint(), unknownFromIndex(), UnmarkEmpty, UnmarkLastRedundant, and var.
Referenced by rollback().
undoLastConstraint()
virtual void mlir::SimplexBase::undoLastConstraint () protected pure virtual
Undo the addition of the last constraint.
This will only be called from undo, when rolling back.
Implemented in mlir::LexSimplex.
Referenced by mlir::LexSimplex::getSnapshot(), and undo().
unknownFromColumn() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromColumn (unsigned col) const protected
Returns the unknown associated with col.
Definition at line 35 of file Simplex.cpp.
References colUnknown, nCol, and unknownFromIndex().
Referenced by mlir::LexSimplex::getLexMinPivotColumn(), swapColumns(), and swapRowWithCol().
unknownFromColumn() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromColumn (unsigned col) protected
Returns the unknown associated with col.
Definition at line 50 of file Simplex.cpp.
References colUnknown, nCol, and unknownFromIndex().
unknownFromIndex() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromIndex (int index) const protected
Returns the unknown associated with index.
Definition at line 30 of file Simplex.cpp.
References con, and var.
Referenced by mlir::Simplex::makeProduct(), undo(), unknownFromColumn(), and unknownFromRow().
unknownFromIndex() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromIndex (int index) protected
Returns the unknown associated with index.
Definition at line 45 of file Simplex.cpp.
References con, and var.
unknownFromRow() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromRow (unsigned row) const protected
Returns the unknown associated with row.
Definition at line 40 of file Simplex.cpp.
References nRow, rowUnknown, and unknownFromIndex().
Referenced by pivot(), swapRows(), and swapRowWithCol().
unknownFromRow() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromRow (unsigned row) protected
Returns the unknown associated with row.
Definition at line 55 of file Simplex.cpp.
References nRow, rowUnknown, and unknownFromIndex().
Member Data Documentation
colUnknown
SmallVector<int, 8> mlir::SimplexBase::colUnknown protected
Definition at line 349 of file Simplex.h.
Referenced by appendVariable(), mlir::LexSimplex::getLexMinPivotColumn(), getSnapshotBasis(), mlir::Simplex::makeProduct(), print(), SimplexBase(), swapColumns(), swapRowWithCol(), undo(), and unknownFromColumn().
con
SmallVector<Unknown, 8> mlir::SimplexBase::con protected
These hold information about each unknown.
Definition at line 352 of file Simplex.h.
Referenced by mlir::Simplex::addInequality(), addRow(), mlir::Simplex::computeOptimum(), mlir::Simplex::detectRedundant(), findAnyPivotRow(), getNumConstraints(), mlir::Simplex::isBoundedAlongConstraint(), mlir::Simplex::isMarkedRedundant(), mlir::Simplex::makeProduct(), print(), removeLastConstraintRowOrientation(), mlir::LexSimplex::undoLastConstraint(), and unknownFromIndex().
empty
bool mlir::SimplexBase::empty protected
This is true if the tableau has been detected to be empty, false otherwise.
Definition at line 332 of file Simplex.h.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::detectRedundant(), mlir::Simplex::findIntegerSample(), getRationalSample(), mlir::Simplex::getSamplePointIfIntegral(), mlir::Simplex::isBoundedAlongConstraint(), isEmpty(), mlir::Simplex::isUnbounded(), mlir::Simplex::makeProduct(), markEmpty(), print(), and undo().
nCol
unsigned mlir::SimplexBase::nCol protected
The number of columns in the tableau, including the common denominator and the constant column.
Definition at line 321 of file Simplex.h.
Referenced by addRow(), appendVariable(), mlir::LexSimplex::getLexMinPivotColumn(), mlir::Simplex::makeProduct(), mlir::LexSimplex::moveRowUnknownToColumn(), normalizeRow(), pivot(), print(), swapColumns(), undo(), and unknownFromColumn().
nRedundant
unsigned mlir::SimplexBase::nRedundant protected
The number of redundant rows in the tableau.
These are the first nRedundant rows.
Definition at line 325 of file Simplex.h.
Referenced by findAnyPivotRow(), mlir::Simplex::isMarkedRedundant(), mlir::Simplex::makeProduct(), pivot(), and undo().
nRow
unsigned mlir::SimplexBase::nRow protected
The number of rows in the tableau.
Definition at line 317 of file Simplex.h.
Referenced by addRow(), findAnyPivotRow(), mlir::Simplex::makeProduct(), mlir::LexSimplex::maybeGetViolatedRow(), pivot(), print(), removeLastConstraintRowOrientation(), and unknownFromRow().
rowUnknown
SmallVector<int, 8> mlir::SimplexBase::rowUnknown protected
These hold the indexes of the unknown at a given row or column position.
We keep these as signed integers since that makes it convenient to check if an index corresponds to a variable or a constraint by checking the sign.
colUnknown is padded with two null indexes at the front since the first two columns don't correspond to any unknowns.
Definition at line 349 of file Simplex.h.
Referenced by addRow(), mlir::Simplex::makeProduct(), pivot(), print(), removeLastConstraintRowOrientation(), swapRows(), swapRowWithCol(), and unknownFromRow().
savedBases
SmallVector<SmallVector<int, 8>, 8> mlir::SimplexBase::savedBases protected
Holds a vector of bases.
The ith saved basis is the basis that should be restored when processing the ith occurrance of UndoLogEntry::RestoreBasis in undoLog. This is used by getSnapshotBasis.
Definition at line 340 of file Simplex.h.
Referenced by getSnapshotBasis(), and undo().
tableau
Matrix mlir::SimplexBase::tableau protected
The matrix representing the tableau.
Definition at line 328 of file Simplex.h.
Referenced by addRow(), appendVariable(), mlir::Simplex::computeRowOptimum(), findAnyPivotRow(), mlir::LexSimplex::getLexMinPivotColumn(), getRationalSample(), mlir::Simplex::makeProduct(), mlir::LexSimplex::moveRowUnknownToColumn(), normalizeRow(), pivot(), print(), removeLastConstraintRowOrientation(), mlir::LexSimplex::rowIsViolated(), swapColumns(), swapRows(), and undo().
undoLog
SmallVector<UndoLogEntry, 8> mlir::SimplexBase::undoLog protected
Holds a log of operations, used for rolling back to a previous state.
Definition at line 335 of file Simplex.h.
Referenced by addRow(), appendVariable(), getSnapshot(), getSnapshotBasis(), mlir::Simplex::isMarkedRedundant(), markEmpty(), and rollback().
usingBigM
const bool mlir::SimplexBase::usingBigM protected
Stores whether or not a big M column is present in the tableau.
Definition at line 314 of file Simplex.h.
Referenced by addRow(), getNumFixedCols(), and getRationalSample().
var
SmallVector<Unknown, 8> mlir::SimplexBase::var protected
Definition at line 352 of file Simplex.h.
Referenced by addRow(), appendVariable(), mlir::Simplex::findIntegerSample(), mlir::LexSimplex::getLexMinPivotColumn(), getNumVariables(), getRationalSample(), mlir::Simplex::getSamplePointIfIntegral(), mlir::Simplex::isUnbounded(), mlir::Simplex::makeProduct(), print(), SimplexBase(), undo(), and unknownFromIndex().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Simplex.h
lib/Analysis/Presburger/Simplex.cpp