MLIR: mlir::LexSimplex Class Reference
mlir::LexSimplex Class Reference
Simplex class using the lexicographic pivot rule.
#include "mlir/Analysis/Presburger/Simplex.h"
Public Member Functions
LexSimplex (unsigned nVar)
LexSimplex (const IntegerPolyhedron &constraints)
~LexSimplex () override=default
void addInequality (ArrayRef< int64_t > coeffs) final
Add an inequality to the tableau.
unsigned getSnapshot ()
Get a snapshot of the current state. This is used for rolling back.
Optional< SmallVector< Fraction, 8 > > getRationalLexMin ()
Return the lexicographically minimum rational solution to the constraints.
Public Member Functions inherited from mlir::SimplexBase
SimplexBase ()=delete
virtual ~SimplexBase ()=default
SimplexBase (unsigned nVar, bool mustUseBigM)
Construct a SimplexBase with the specified number of variables and fixed columns.
bool isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
unsigned getNumVariables () const
Returns the number of variables in the tableau.
unsigned getNumConstraints () const
Returns the number of constraints in the tableau.
void addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
void appendVariable (unsigned count=1)
Add new variables to the end of the list of variables.
void markEmpty ()
Mark the tableau as being empty.
unsigned getSnapshot () const
Get a snapshot of the current state.
unsigned getSnapshotBasis ()
Get a snapshot of the current state including the basis.
void rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
void intersectIntegerPolyhedron (const IntegerPolyhedron &poly)
Add all the constraints from the given IntegerPolyhedron.
Optional< SmallVector< Fraction, 8 > > getRationalSample () const
Returns the current sample point, which may contain non-integer (rational) coordinates.
void print (raw_ostream &os) const
Print the tableau's internal state.
void dump () const
Protected Member Functions
void undoLastConstraint () final
Undo the addition of the last constraint.
void restoreRationalConsistency ()
Make the tableau configuration consistent.
bool rowIsViolated (unsigned row) const
Return whether the specified row is violated;.
Optional< unsigned > maybeGetViolatedRow () const
Get a constraint row that is violated, if one exists.
unsigned getLexMinPivotColumn (unsigned row, unsigned colA, unsigned colB) const
Given two potential pivot columns for a row, return the one that results in the lexicographically smallest sample vector.
LogicalResult moveRowUnknownToColumn (unsigned row)
Try to move the specified row to column orientation while preserving the lexicopositivity of the basis transform.
Protected Member Functions inherited from mlir::SimplexBase
Optional< unsigned > findAnyPivotRow (unsigned col)
Return any row that this column can be pivoted with, ignoring tableau consistency.
void swapRowWithCol (unsigned row, unsigned col)
Swap the row with the column in the tableau's data structures but not the tableau itself.
void pivot (unsigned row, unsigned col)
Pivot the row with the column.
void pivot (Pivot pair)
const Unknown & unknownFromIndex (int index) const
Returns the unknown associated with index.
const Unknown & unknownFromColumn (unsigned col) const
Returns the unknown associated with col.
const Unknown & unknownFromRow (unsigned row) const
Returns the unknown associated with row.
Unknown & unknownFromIndex (int index)
Returns the unknown associated with index.
Unknown & unknownFromColumn (unsigned col)
Returns the unknown associated with col.
Unknown & unknownFromRow (unsigned row)
Returns the unknown associated with row.
unsigned addRow (ArrayRef< int64_t > coeffs, bool makeRestricted=false)
Add a new row to the tableau and the associated data structures.
void normalizeRow (unsigned row)
Normalize the given row by removing common factors between the numerator and the denominator.
void swapRows (unsigned i, unsigned j)
Swap the two rows/columns in the tableau and associated data structures.
void swapColumns (unsigned i, unsigned j)
void removeLastConstraintRowOrientation ()
Remove the last constraint, which must be in row orientation.
void undo (UndoLogEntry entry)
Undo the operation represented by the log entry.
unsigned getNumFixedCols () const
Return the number of fixed columns, as described in the constructor above, this is the number of columns beyond those for the variables in var.
Additional Inherited Members
Protected Types inherited from mlir::SimplexBase
enum Orientation { Orientation::Row, Orientation::Column }
enum UndoLogEntry {
UndoLogEntry::RemoveLastConstraint, UndoLogEntry::RemoveLastVariable, UndoLogEntry::UnmarkEmpty, UndoLogEntry::UnmarkLastRedundant,
UndoLogEntry::RestoreBasis
}
Enum to denote operations that need to be undone during rollback.
Protected Attributes inherited from mlir::SimplexBase
const bool usingBigM
Stores whether or not a big M column is present in the tableau.
unsigned nRow
The number of rows in the tableau.
unsigned nCol
The number of columns in the tableau, including the common denominator and the constant column.
unsigned nRedundant
The number of redundant rows in the tableau.
Matrix tableau
The matrix representing the tableau.
bool empty
This is true if the tableau has been detected to be empty, false otherwise.
SmallVector< UndoLogEntry, 8 > undoLog
Holds a log of operations, used for rolling back to a previous state.
SmallVector< SmallVector< int, 8 >, 8 > savedBases
Holds a vector of bases.
SmallVector< int, 8 > rowUnknown
These hold the indexes of the unknown at a given row or column position.
SmallVector< int, 8 > colUnknown
SmallVector< Unknown, 8 > con
These hold information about each unknown.
SmallVector< Unknown, 8 > var
Detailed Description
Simplex class using the lexicographic pivot rule.
Used for lexicographic optimization. The implementation of this class is based on the paper "Parametric Integer Programming" by Paul Feautrier.
This does not directly support negative-valued variables, so it uses the big M parameter trick to make all the variables non-negative. Basically we introduce an artifical variable M that is considered to have a value of +infinity and instead of the variables x, y, z, we internally use variables M + x, M + y, M + z, which are now guaranteed to be non-negative. See the documentation for Simplex for more details. The whole algorithm is performed without having to fix a "big enough" value of the big M parameter; it is just considered to be infinite throughout and it never appears in the final outputs. We will deal with sample values throughout that may in general be some linear expression involving M like pM + q or aM + b. We can compare these with each other. They have a total order: aM + b < pM + q iff a < p or (a == p and b < q). In particular, aM + b < 0 iff a < 0 or (a == 0 and b < 0).
Initially all the constraints to be added are added as rows, with no attempt to keep the tableau consistent. Pivots are only performed when some query is made, such as a call to getRationalLexMin. Care is taken to always maintain a lexicopositive basis transform, explained below.
Let the variables be x = (x_1, ... x_n). Let the basis unknowns at a particular point be y = (y_1, ... y_n). We know that x = A*y + b for some n x n matrix A and n x 1 column vector b. We want every column in A to be lexicopositive, i.e., have at least one non-zero element, with the first such element being positive. This property is preserved throughout the operation of LexSimplex. Note that on construction, the basis transform A is the indentity matrix and so every column is lexicopositive. Note that for LexSimplex, for the tableau to be consistent we must have non-negative sample values not only for the constraints but also for the variables. So if the tableau is consistent then x >= 0 and y >= 0, by which we mean every element in these vectors is non-negative. (note that this is a different concept from lexicopositivity!)
When we arrive at a basis such the basis transform is lexicopositive and the tableau is consistent, the sample point is the lexiographically minimum point in the polytope. We will show that A*y is zero or lexicopositive when y >= 0. Adding a lexicopositive vector to b will make it lexicographically bigger, so A*y + b is lexicographically bigger than b for any y >= 0 except y = 0. This shows that no point lexicographically smaller than x = b can be obtained. Since we already know that x = b is valid point in the space, this shows that x = b is the lexicographic minimum.
Proof that A*y is lexicopositive or zero when y > 0. Recall that every column of A is lexicopositive. Begin by considering A_1, the first row of A. If this row is all zeros, then (A*y)_1 = (A_1)*y = 0; proceed to the next row. If we run out of rows, A*y is zero and we are done; otherwise, we encounter some row A_i that has a non-zero element. Every column is lexicopositive and so has some positive element before any negative elements occur, so the element in this row for any column, if non-zero, must be positive. Consider (A*y)_i = (A_i)*y. All the elements in both vectors are non-negative, so if this is non-zero then it must be positive. Then the first non-zero element of A*y is positive so A*y is lexicopositive.
Otherwise, if (A_i)*y is zero, then for every column j that had a non-zero element in A_i, y_j is zero. Thus these columns have no contribution to A*y and we can completely ignore these columns of A. We now continue downwards, looking for rows of A that have a non-zero element other than in the ignored columns. If we find one, say A_k, once again these elements must be positive since they are the first non-zero element in each of these columns, so if (A_k)*y is not zero then we have that A*y is lexicopositive and if not we ignore more columns; eventually if all these dot products become zero then A*y is zero and we are done.
Definition at line 420 of file Simplex.h.
Constructor & Destructor Documentation
LexSimplex() [1/2]
mlir::LexSimplex::LexSimplex (unsigned nVar) inline explicit
Definition at line 422 of file Simplex.h.
LexSimplex() [2/2]
mlir::LexSimplex::LexSimplex (const IntegerPolyhedron & constraints) inline explicit
Definition at line 424 of file Simplex.h.
References mlir::SimplexBase::intersectIntegerPolyhedron().
~LexSimplex()
mlir::LexSimplex::~LexSimplex () override default
Member Function Documentation
addInequality()
void mlir::LexSimplex::addInequality (ArrayRef< int64_t > coeffs) inline final virtual
Add an inequality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
This just adds the inequality to the tableau and does not try to create a consistent tableau configuration.
Implements mlir::SimplexBase.
Definition at line 436 of file Simplex.h.
References mlir::SimplexBase::addRow().
getLexMinPivotColumn()
unsigned mlir::LexSimplex::getLexMinPivotColumn (unsigned row, unsigned colA, unsigned colB) const protected
Given two potential pivot columns for a row, return the one that results in the lexicographically smallest sample vector.
Definition at line 271 of file Simplex.cpp.
References mlir::SimplexBase::Column, mlir::SimplexBase::colUnknown, mlir::SimplexBase::nCol, mlir::SimplexBase::tableau, mlir::SimplexBase::unknownFromColumn(), and mlir::SimplexBase::var.
getRationalLexMin()
Optional< SmallVector< Fraction, 8 > > mlir::LexSimplex::getRationalLexMin ()
Return the lexicographically minimum rational solution to the constraints.
Definition at line 160 of file Simplex.cpp.
References mlir::SimplexBase::getRationalSample().
Referenced by mlir::IntegerPolyhedron::getRationalLexMin().
getSnapshot()
unsigned mlir::LexSimplex::getSnapshot () inline
Get a snapshot of the current state. This is used for rolling back.
Definition at line 441 of file Simplex.h.
References mlir::SimplexBase::getSnapshotBasis(), and mlir::SimplexBase::undoLastConstraint().
maybeGetViolatedRow()
Optional< unsigned > mlir::LexSimplex::maybeGetViolatedRow () const protected
Get a constraint row that is violated, if one exists.
Otherwise, return an empty optional.
Definition at line 173 of file Simplex.cpp.
References mlir::SimplexBase::nRow.
moveRowUnknownToColumn()
LogicalResult mlir::LexSimplex::moveRowUnknownToColumn (unsigned row) protected
Try to move the specified row to column orientation while preserving the lexicopositivity of the basis transform.
If this is not possible, return failure. This only occurs when the constraints have no solution; the tableau will be marked empty in such a case.
Definition at line 253 of file Simplex.cpp.
References mlir::failure(), mlir::SimplexBase::markEmpty(), mlir::SimplexBase::nCol, mlir::SimplexBase::pivot(), mlir::success(), and mlir::SimplexBase::tableau.
restoreRationalConsistency()
void mlir::LexSimplex::restoreRationalConsistency () protected
Make the tableau configuration consistent.
Definition at line 183 of file Simplex.cpp.
References mlir::failed().
rowIsViolated()
bool mlir::LexSimplex::rowIsViolated (unsigned row) const protected
Return whether the specified row is violated;.
Definition at line 165 of file Simplex.cpp.
References mlir::SimplexBase::tableau.
undoLastConstraint()
void mlir::LexSimplex::undoLastConstraint () final protected virtual
Undo the addition of the last constraint.
This is only called while rolling back.
Implements mlir::SimplexBase.
Definition at line 681 of file Simplex.cpp.
References mlir::SimplexBase::Column, mlir::SimplexBase::con, mlir::SimplexBase::findAnyPivotRow(), mlir::SimplexBase::pivot(), and mlir::SimplexBase::removeLastConstraintRowOrientation().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Simplex.h
lib/Analysis/Presburger/Simplex.cpp