MLIR: lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp File Reference
ElementwiseOpFusion.cpp File Reference
#include <utility>
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Functions
static AffineMap getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp (OpOperand *producerOpOperand, AffineMap producerResultIndexMap, AffineMap fusedConsumerArgIndexMap)
Append to fusedOpIndexingMapAttrs the indexing maps for the operands of the producer to use in the fused operation given the indexing map of the result of the producer in the consumer.
static bool areElementwiseOpsFusable (GenericOp producer, GenericOp consumer, OpOperand *consumerOpOperand)
Conditions for elementwise fusion of generic operations.
static void generateFusedElementwiseOpRegion (PatternRewriter &rewriter, GenericOp fusedOp, AffineMap consumerToProducerLoopsMap, OpOperand *consumerOpOperand, unsigned nloops)
Generate the region of the fused tensor operation.
static Optional< SmallVector< Value > > fuseElementwiseOpsImpl (GenericOp producer, OpOperand *consumerOpOperand, const ControlElementwiseOpsFusionFn &controlFn, PatternRewriter &rewriter)
static Optional< SmallVector< Value > > fuseElementwiseOps (PatternRewriter &rewriter, OpOperand *consumerOpOperand, GenericOp producer, const ControlElementwiseOpsFusionFn &controlFn)
template<typename TensorReshapeOp >
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, TensorReshapeOp reshapeOp)
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
static bool isTensorReshapeOpFoldableByLinearization (tensor::ExpandShapeOp expandOp, AffineMap useIndexMap, bool asProducer)
static bool isTensorReshapeOpFoldableByLinearization (tensor::CollapseShapeOp collapseOp, AffineMap useIndexMap, bool asProducer)
template<typename TensorReshapeOp >
static bool isUnitDimExpansionOnly (TensorReshapeOp reshapeOp)
Check if the reshape operation is only expansion into/collapsing of unit-dimension.
static bool isFusableWithReshapeByDimExpansion (GenericOp genericOp, OpOperand *fusableOpOperand)
Conditions for folding a generic operation with a reshape op by expanding the iteration space dimensionality for tensor operations.
static LogicalResult isGenericOpExpandable (GenericOp genericOp, const ExpansionInfo &expansionInfo, PatternRewriter &rewriter)
Epanding the body of a linalg operation requires adaptations of the accessed loop indices.
static AffineMap getIndexingMapInExpandedOp (OpBuilder &builder, AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Return the indexing map to use in the expanded op for a given the indexingMap of the original operation.
static RankedTensorType getExpandedType (RankedTensorType originalType, AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Return the type of the operand/result to use in the expanded op given the type in the original op.
static SmallVector< ReassociationIndices > getReassociationForExpansion (AffineMap indexingMap, const ExpansionInfo &expansionInfo)
Returns the reassociation maps to use in the tensor.expand_shape operation to convert the operands of the original operation to operands of the expanded operation.
static void updateExpandedGenericOpRegion (PatternRewriter &rewriter, Location loc, Region &fusedRegion, const ExpansionInfo &expansionInfo)
Update the body of an expanded linalg operation having index semantics.
static Optional< SmallVector< Value > > fuseWithReshapeByExpansion (GenericOp genericOp, Operation *reshapeOp, OpOperand *fusableOpOperand, PatternRewriter &rewriter)
Implements the fusion of a tensor_collapse_shape or a tensor_expand_shape op and a generic op as explained in isFusableWithReshapeByExpansion.
static SmallVector< ReassociationIndices > getDomainReassociation (AffineMap indexingMap, ArrayRef< ReassociationIndices > rangeReassociation)
For an indexingMap that is a projected permutation, if the range is to be collapsed using the given reassociation, get the reassociation in the domain that would keep the map a projected permutation.
static bool isDimSequencePreserved (AffineMap indexingMap, ReassociationIndicesRef dimSequence)
For a given dimSequence, check if the sequence is conserved in the indexingMap.
static bool isFusableWithReshapeByDimCollapse (GenericOp genericOp, OpOperand *fusableOperand, ArrayRef< ReassociationIndices > reassociation)
static SmallVector< StringRef > getCollapsedOpIteratorTypes (ArrayRef< Attribute > iteratorTypes, CollapsingInfo &collapsingInfo)
Get the iterator types for the collapsed operation given the original iterator types and collapsed dimensions.
static AffineMap getCollapsedOpIndexingMap (AffineMap indexingMap, CollapsingInfo &collapsingInfo)
Compute the indexing map in the collapsed op that corresponds to the given indexingMap of the original operation.
static SmallVector< ReassociationIndices > getOperandReassociation (AffineMap indexingMap, CollapsingInfo &collapsingInfo)
Return the reassociation indices to use to collapse the operand when the iteration space of a generic op is collapsed.
static Value getCollapsedOpOperand (Location loc, GenericOp genericOp, OpOperand *opOperand, CollapsingInfo &collapsingInfo, OpBuilder &builder)
Get the new value to use for a given OpOperand in the collapsed operation.
void generateCollapsedIndexingRegion (Location loc, Block *block, CollapsingInfo &collapsingInfo, ValueRange loopRange, PatternRewriter &rewriter)
Modify the linalg.index operations in the original generic op, to its value in the collapsed operation.
static Optional< SmallVector< Value > > fuseWithReshapeByCollapsing (GenericOp genericOp, Operation *reshapeOp, OpOperand *fusableOpOperand, PatternRewriter &rewriter)
Implementation of fusion with reshape operation by collapsing dimensions.
static SmallVector< ReassociationIndices > getReassociationIndices (ArrayRef< AffineMap > maps)
Function Documentation
areElementwiseOpsFusable()
static bool areElementwiseOpsFusable (GenericOp producer, GenericOp consumer, OpOperand * consumerOpOperand) static
Conditions for elementwise fusion of generic operations.
Definition at line 68 of file ElementwiseOpFusion.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::isPermutation().
Referenced by fuseElementwiseOpsImpl().
fuseElementwiseOps()
static Optional<SmallVector<Value> > fuseElementwiseOps (PatternRewriter & rewriter, OpOperand * consumerOpOperand, GenericOp producer, const ControlElementwiseOpsFusionFn & controlFn) static
Definition at line 354 of file ElementwiseOpFusion.cpp.
References mlir::failure(), fuseElementwiseOpsImpl(), mlir::RewriterBase::replaceOp(), and mlir::success().
fuseElementwiseOpsImpl()
static Optional<SmallVector<Value> > fuseElementwiseOpsImpl (GenericOp producer, OpOperand * consumerOpOperand, const ControlElementwiseOpsFusionFn & controlFn, PatternRewriter & rewriter) static
Definition at line 250 of file ElementwiseOpFusion.cpp.
References areElementwiseOpsFusable(), mlir::AffineMap::compose(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), generateFusedElementwiseOpRegion(), mlir::Builder::getAffineMapArrayAttr(), getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp(), mlir::detail::IROperandBase::getOwner(), and mlir::inversePermutation().
Referenced by fuseElementwiseOps().
fuseWithReshapeByCollapsing()
static Optional<SmallVector<Value> > fuseWithReshapeByCollapsing (GenericOp genericOp, Operation * reshapeOp, OpOperand * fusableOpOperand, PatternRewriter & rewriter) static
Implementation of fusion with reshape operation by collapsing dimensions.
Definition at line 1455 of file ElementwiseOpFusion.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), mlir::Block::front(), generateCollapsedIndexingRegion(), mlir::Block::getArguments(), getCollapsedOpIndexingMap(), getCollapsedOpIteratorTypes(), getCollapsedOpOperand(), getDomainReassociation(), mlir::Builder::getFusedLoc(), mlir::Operation::getLoc(), getOperandReassociation(), getReassociationIndices(), mlir::Value::getType(), isFusableWithReshapeByDimCollapse(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::RewriterBase::mergeBlocks(), mlir::RewriterBase::notifyMatchFailure(), mlir::Range::offset, mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::Range::size, mlir::Range::stride, and mlir::success().
fuseWithReshapeByExpansion()
static Optional<SmallVector<Value> > fuseWithReshapeByExpansion (GenericOp genericOp, Operation * reshapeOp, OpOperand * fusableOpOperand, PatternRewriter & rewriter) static
Implements the fusion of a tensor_collapse_shape or a tensor_expand_shape op and a generic op as explained in isFusableWithReshapeByExpansion.
Assumes that those conditions have been satisfied.
Definition at line 945 of file ElementwiseOpFusion.cpp.
References mlir::Region::begin(), mlir::RewriterBase::cloneRegionBefore(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::AffineMap::get(), getExpandedType(), getIndexingMapInExpandedOp(), mlir::getParallelIteratorTypeName(), getReassociationForExpansion(), mlir::ValueRange::getTypes(), isFusableWithReshapeByDimExpansion(), isGenericOpExpandable(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::reshapeLikeShapesAreCompatible(), mlir::success(), and updateExpandedGenericOpRegion().
generateCollapsedIndexingRegion()
void generateCollapsedIndexingRegion (Location loc, Block * block, CollapsingInfo & collapsingInfo, ValueRange loopRange, PatternRewriter & rewriter)
Modify the linalg.index operations in the original generic op, to its value in the collapsed operation.
Definition at line 1416 of file ElementwiseOpFusion.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Block::getOps(), mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by fuseWithReshapeByCollapsing().
generateFusedElementwiseOpRegion()
static void generateFusedElementwiseOpRegion (PatternRewriter & rewriter, GenericOp fusedOp, AffineMap consumerToProducerLoopsMap, OpOperand * consumerOpOperand, unsigned nloops) static
Generate the region of the fused tensor operation.
The region of the fused op must be empty.
Definition at line 139 of file ElementwiseOpFusion.cpp.
References mlir::Block::addArgument(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::Block::front(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), mlir::BlockArgument::getLoc(), mlir::Block::getNumArguments(), mlir::OpOperand::getOperandNumber(), mlir::Block::getOperations(), mlir::detail::IROperandBase::getOwner(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), max(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by fuseElementwiseOpsImpl().
getCollapsedOpIndexingMap()
static AffineMap getCollapsedOpIndexingMap (AffineMap indexingMap, CollapsingInfo & collapsingInfo) static
Compute the indexing map in the collapsed op that corresponds to the given indexingMap of the original operation.
Definition at line 1356 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by fuseWithReshapeByCollapsing().
getCollapsedOpIteratorTypes()
static SmallVector<StringRef> getCollapsedOpIteratorTypes (ArrayRef< Attribute > iteratorTypes, CollapsingInfo & collapsingInfo) static
Get the iterator types for the collapsed operation given the original iterator types and collapsed dimensions.
Definition at line 1338 of file ElementwiseOpFusion.cpp.
Referenced by fuseWithReshapeByCollapsing().
getCollapsedOpOperand()
static Value getCollapsedOpOperand (Location loc, GenericOp genericOp, OpOperand * opOperand, CollapsingInfo & collapsingInfo, OpBuilder & builder) static
Get the new value to use for a given OpOperand in the collapsed operation.
Definition at line 1394 of file ElementwiseOpFusion.cpp.
References mlir::OpBuilder::create(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::AffineMap::getNumResults(), and getOperandReassociation().
Referenced by fuseWithReshapeByCollapsing().
getDomainReassociation()
static SmallVector<ReassociationIndices> getDomainReassociation (AffineMap indexingMap, ArrayRef< ReassociationIndices > rangeReassociation) static
For an indexingMap that is a projected permutation, if the range is to be collapsed using the given reassociation, get the reassociation in the domain that would keep the map a projected permutation.
Definition at line 1158 of file ElementwiseOpFusion.cpp.
References mlir::AffineExpr::cast(), mlir::AffineMap::getNumDims(), mlir::AffineDimExpr::getPosition(), mlir::AffineMap::getResult(), and mlir::AffineMap::isProjectedPermutation().
Referenced by fuseWithReshapeByCollapsing(), and isFusableWithReshapeByDimCollapse().
getExpandedType()
static RankedTensorType getExpandedType (RankedTensorType originalType, AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Return the type of the operand/result to use in the expanded op given the type in the original op.
Definition at line 864 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
getIndexingMapInExpandedOp()
static AffineMap getIndexingMapInExpandedOp (OpBuilder & builder, AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Return the indexing map to use in the expanded op for a given the indexingMap of the original operation.
Definition at line 846 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp()
static AffineMap getIndexingMapOfProducerOperandsInCoordinatesOfFusedOp (OpOperand * producerOpOperand, AffineMap producerResultIndexMap, AffineMap fusedConsumerArgIndexMap) static
Append to fusedOpIndexingMapAttrs the indexing maps for the operands of the producer to use in the fused operation given the indexing map of the result of the producer in the consumer.
Definition at line 38 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::compose(), mlir::detail::IROperandBase::getOwner(), and mlir::inversePermutation().
Referenced by areElementwiseOpsFusable(), and fuseElementwiseOpsImpl().
getOperandReassociation()
static SmallVector<ReassociationIndices> getOperandReassociation (AffineMap indexingMap, CollapsingInfo & collapsingInfo) static
Return the reassociation indices to use to collapse the operand when the iteration space of a generic op is collapsed.
Definition at line 1377 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByCollapsing(), and getCollapsedOpOperand().
getReassociationForExpansion()
static SmallVector<ReassociationIndices> getReassociationForExpansion (AffineMap indexingMap, const ExpansionInfo & expansionInfo) static
Returns the reassociation maps to use in the tensor.expand_shape operation to convert the operands of the original operation to operands of the expanded operation.
The same method is used to compute the tensor.collapse_shape used to collapse the result of the expanded op to get the value that can replace all uses of the results of the original op.
Definition at line 883 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::getResults().
Referenced by fuseWithReshapeByExpansion().
getReassociationIndices()
static SmallVector<ReassociationIndices> getReassociationIndices (ArrayRef< AffineMap > maps) static
Definition at line 1614 of file ElementwiseOpFusion.cpp.
References mlir::Region::begin(), mlir::Block::begin(), mlir::RewriterBase::cancelRootUpdate(), mlir::Value::cast(), mlir::RewriterBase::cloneRegionBefore(), mlir::concatAffineMaps(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Block::front(), mlir::AffineMap::get(), mlir::DenseElementsAttr::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Value::getDefiningOp(), mlir::AffineMap::getDimPosition(), getElementType(), mlir::Builder::getFusedLoc(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::AffineMap::getNumResults(), mlir::getParallelIteratorTypeName(), mlir::AffineDimExpr::getPosition(), getShape(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::DenseElementsAttr::getSplatValue(), mlir::Block::getTerminator(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::DenseElementsAttr::getType(), mlir::RewriterBase::inlineRegionBefore(), mlir::inversePermutation(), mlir::DenseElementsAttr::isSplat(), mlir::m_Constant(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::RewriterBase::startRootUpdate(), and mlir::success().
Referenced by fuseWithReshapeByCollapsing(), getNumElements(), isFusableWithReshapeByDimCollapse(), and parseGlobalMemrefOpTypeAndInitialValue().
isDimSequencePreserved()
static bool isDimSequencePreserved (AffineMap indexingMap, ReassociationIndicesRef dimSequence) static
For a given dimSequence, check if the sequence is conserved in the indexingMap.
indexingMap is expected to be a projected permutation. Non-existence of the sequence returns true as well.
Definition at line 1197 of file ElementwiseOpFusion.cpp.
References mlir::detail::enumerate(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by isFusableWithReshapeByDimCollapse().
isFusableWithReshapeByDimCollapse()
static bool isFusableWithReshapeByDimCollapse (GenericOp genericOp, OpOperand * fusableOperand, ArrayRef< ReassociationIndices > reassociation) static
Definition at line 1239 of file ElementwiseOpFusion.cpp.
References mlir::detail::enumerate(), getDomainReassociation(), getReassociationIndices(), isDimSequencePreserved(), mlir::isParallelIterator(), and mlir::isReductionIterator().
Referenced by fuseWithReshapeByCollapsing().
isFusableWithReshapeByDimExpansion()
static bool isFusableWithReshapeByDimExpansion (GenericOp genericOp, OpOperand * fusableOpOperand) static
Conditions for folding a generic operation with a reshape op by expanding the iteration space dimensionality for tensor operations.
These are preconditions assumed by foldReshapeByDimExpansion which implements the following fusion pattern.
Consider
c = linalg.generic ins(a, b : memref<?x?x?xf32>, memref<?x?xf32>) indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d2, d1)>] d = tensor.expand_shape c [[0, 1], [2], [3, 4, 5]] : tensor<?x?x?xf32> into tensor<?x?x?x?x?x?xf32>
The reshape can be folded into the genericOp if its loop dimensionality is increased to match the result (operand) of the tensor_expand_shape. The indexing_map of the fused tensor in the genericOp and the reassociation map helps compute the indexing maps of the modified op. For the above example, based on the reassociation map it can be concluded that
The loop used to access the first dimension of the fused tensor is split into two.
The loop used to access the second dimension of the fused tensor is kept as is.
The loop used to access the third dimension of the fused tensor is split into three.
i.e. (e0, e1, e2, e3, e4) is the domain of the indexing map of the modified op, then
d0 -> e0, e1 d1 -> e2, e3, e4 d2 -> e5
substituting this, the generic op can be rewritten as
d = linalg.generic ins(%0, %1 :) indexing_maps = [affine_map<(e0, e1, e2, e3, e4, e5) -> (e2, e3, e4, e0, e1, e5)>, affine_map<(e0, e1, e2, e3, e4, e5) -> (e2, e3, e4, e5)>, affine_map<(e0, e1, e2, e3, e4, e5) -> (e0, e1, e5, e2, e3, e4)>]
Since operands to the linalg generic are now 5D, reshapes can be introduced to make it consistent
%0 = tensor.expand_shape a [[0, 1, 2], [3, 4], [5]] : tensor<?x?x?xf32> into tensor<?x?x?x?x?x?xf32> %1 = tensor.expand_shape b [[0, 1, 2], [3]] : tensor<?x?x?xf32> into tensor<?x?x?x?xf32>
The added reshapes are again expanding patterns, so they will get fused with its producers if possible.
Definition at line 710 of file ElementwiseOpFusion.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::getParallelIteratorTypeName(), mlir::AffineMap::getResults(), mlir::RewriterBase::notifyMatchFailure(), and mlir::success().
Referenced by fuseWithReshapeByExpansion().
isGenericOpExpandable()
static LogicalResult isGenericOpExpandable (GenericOp genericOp, const ExpansionInfo & expansionInfo, PatternRewriter & rewriter) static
Epanding the body of a linalg operation requires adaptations of the accessed loop indices.
Specifically, access of indices in the original operation need to be replaced with linearizations of indices in the expanded op. That requires the shape of the expanded dimensions to be static (at least all but the most significant). For now check that these are all statically sized. Note that this could be extended to handle dynamic case, but the implementation below uses affine.apply which seems to have issues when the shapes are not static.
Definition at line 824 of file ElementwiseOpFusion.cpp.
References mlir::RewriterBase::notifyMatchFailure(), and mlir::success().
Referenced by fuseWithReshapeByExpansion().
isTensorReshapeOpFoldableByLinearization() [1/2]
static bool isTensorReshapeOpFoldableByLinearization (tensor::ExpandShapeOp expandOp, AffineMap useIndexMap, bool asProducer) static
Definition at line 468 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::isPermutation().
Referenced by isUnitDimExpansionOnly().
isTensorReshapeOpFoldableByLinearization() [2/2]
static bool isTensorReshapeOpFoldableByLinearization (tensor::CollapseShapeOp collapseOp, AffineMap useIndexMap, bool asProducer) static
Definition at line 478 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::isPermutation().
isUnitDimExpansionOnly()
template<typename TensorReshapeOp > static bool isUnitDimExpansionOnly (TensorReshapeOp reshapeOp) static
Check if the reshape operation is only expansion into/collapsing of unit-dimension.
Definition at line 489 of file ElementwiseOpFusion.cpp.
References mlir::RewriterBase::cloneRegionBefore(), mlir::concatAffineMaps(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), mlir::Builder::getAffineMapArrayAttr(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), mlir::inversePermutation(), isTensorReshapeOpFoldableByLinearization(), linearizeCollapsedDims(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::startRootUpdate(), mlir::success(), and value.
Referenced by mlir::linalg::skipUnitDimReshape().
linearizeCollapsedDims()
template<typename TensorReshapeOp > static AffineMap linearizeCollapsedDims (AffineMap sourceMap, TensorReshapeOp reshapeOp) static
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
Note that this implicitly assumes that the tensors dimensions are "row-major" ordered logically.
For example:
%0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
and reshape: %1 = tensor.collapse_shape %0 [[0], [0, 1, 2]] : tensor<?x?x4x5xf32> into tensor<?x?xf32>
would be rewritten into: %0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1 * 20 + d2 * 5 + d3)>
Definition at line 425 of file ElementwiseOpFusion.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), mlir::makeCanonicalStridedLayoutExpr(), max(), and value.
Referenced by isUnitDimExpansionOnly().
updateExpandedGenericOpRegion()
static void updateExpandedGenericOpRegion (PatternRewriter & rewriter, Location loc, Region & fusedRegion, const ExpansionInfo & expansionInfo) static
Update the body of an expanded linalg operation having index semantics.
The indices of the original operation need to be recovered by linearizing the indices of the correspoding dimensions of the expanded operation. For now it is assumed that the shapes of the expanded operation needed for linearization are static.
Definition at line 903 of file ElementwiseOpFusion.cpp.
References mlir::bindDims(), mlir::OpBuilder::create(), mlir::Region::front(), mlir::Builder::getContext(), mlir::Block::getOps(), mlir::RewriterBase::replaceOp(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by fuseWithReshapeByExpansion().