MLIR: lib/Dialect/GPU/IR/GPUDialect.cpp File Reference
GPUDialect.cpp File Reference
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/GPU/GPUOpsDialect.cpp.inc"
#include "mlir/Dialect/GPU/GPUOps.cpp.inc"
#include "mlir/Dialect/GPU/GPUOpsAttributes.cpp.inc"
#include "mlir/Dialect/GPU/GPUOpInterfaces.cpp.inc"
#include "mlir/Dialect/GPU/GPUOpsEnums.cpp.inc"
Classes
struct FoldLaunchArguments
Simplify the gpu.launch when the range of a thread or block ID is trivially known to be one.
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
Enumerations
enum GPUMemorySpace { kGenericMemorySpace = 0, kGlobalMemorySpace = 1, kSharedMemorySpace = 3 }
GPU memory space identifiers.
Functions
static ParseResult parseAllReduceOperation (AsmParser &parser, AllReduceOperationAttr &attr)
static void printAllReduceOperation (AsmPrinter &printer, Operation *op, AllReduceOperationAttr attr)
static void printSizeAssignment (OpAsmPrinter &p, KernelDim3 size, KernelDim3 operands, KernelDim3 ids)
static ParseResult parseSizeAssignment (OpAsmParser &parser, MutableArrayRef< OpAsmParser::OperandType > sizes, MutableArrayRef< OpAsmParser::OperandType > regionSizes, MutableArrayRef< OpAsmParser::OperandType > indices)
static ParseResult parseLaunchFuncOperands (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes)
static void printLaunchFuncOperands (OpAsmPrinter &printer, Operation *, OperandRange operands, TypeRange types)
static ParseResult parseAttributions (OpAsmParser &parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > &args, SmallVectorImpl< Type > &argTypes)
Parses a GPU function memory attribution.
static void printAttributions (OpAsmPrinter &p, StringRef keyword, ArrayRef< BlockArgument > values)
static LogicalResult verifyAttributions (Operation *op, ArrayRef< BlockArgument > attributions, unsigned memorySpace)
static ParseResult parseAsyncDependencies (OpAsmParser &parser, Type &asyncTokenType, SmallVectorImpl< OpAsmParser::OperandType > &asyncDependencies)
static void printAsyncDependencies (OpAsmPrinter &printer, Operation *op, Type asyncTokenType, OperandRange asyncDependencies)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static LogicalResult verify (AllocOp op)
static bool isLastMemrefDimUnitStride (MemRefType type)
Return true if the last dimension of the MemRefType has unit stride.
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 1268 of file GPUDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1271 of file GPUDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
GPUMemorySpace
enum GPUMemorySpace
GPU memory space identifiers.
Enumerator
kGenericMemorySpace
Generic memory space identifier.
kGlobalMemorySpace
Global memory space identifier.
kSharedMemorySpace
Shared memory space identifier.
Definition at line 88 of file GPUDialect.cpp.
Function Documentation
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref.cast into the root operation directly.
Definition at line 1151 of file GPUDialect.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
isLastMemrefDimUnitStride()
static bool isLastMemrefDimUnitStride (MemRefType type) static
Return true if the last dimension of the MemRefType has unit stride.
Also return true for memrefs with no strides.
Definition at line 1236 of file GPUDialect.cpp.
References mlir::emitError(), mlir::getStridesAndOffset(), mlir::succeeded(), mlir::success(), and verify().
parseAllReduceOperation()
static ParseResult parseAllReduceOperation (AsmParser & parser, AllReduceOperationAttr & attr) static
Definition at line 315 of file GPUDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::parseOptionalKeyword(), and mlir::success().
parseAsyncDependencies()
static ParseResult parseAsyncDependencies (OpAsmParser & parser, Type & asyncTokenType, SmallVectorImpl< OpAsmParser::OperandType > & asyncDependencies) static
Definition at line 1042 of file GPUDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::OpAsmParser::getNumResults(), mlir::Builder::getType(), mlir::AsmParser::OptionalSquare, mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalKeyword(), and mlir::succeeded().
parseAttributions()
static ParseResult parseAttributions (OpAsmParser & parser, StringRef keyword, SmallVectorImpl< OpAsmParser::OperandType > & args, SmallVectorImpl< Type > & argTypes) static
Parses a GPU function memory attribution.
memory-attribution ::= (workgroup (ssa-id-and-type-list))? (private (ssa-id-and-type-list))?
Note that this function parses only one of the two similar parts, with the keyword provided as argument.
Definition at line 771 of file GPUDialect.cpp.
References mlir::function_interface_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getFunctionType(), mlir::Builder::getI64IntegerAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_interface_impl::getTypeAttrName(), mlir::Builder::getUnitAttr(), mlir::AsmParser::parseColonType(), mlir::function_interface_impl::parseFunctionSignature(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), mlir::succeeded(), and mlir::success().
parseLaunchFuncOperands()
static ParseResult parseLaunchFuncOperands (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes) static
Definition at line 671 of file GPUDialect.cpp.
References mlir::function_interface_impl::parseFunctionArgumentList(), mlir::AsmParser::parseOptionalKeyword(), and mlir::success().
parseSizeAssignment()
static ParseResult parseSizeAssignment (OpAsmParser & parser, MutableArrayRef< OpAsmParser::OperandType > sizes, MutableArrayRef< OpAsmParser::OperandType > regionSizes, MutableArrayRef< OpAsmParser::OperandType > indices) static
Definition at line 477 of file GPUDialect.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32Type(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::AsmParser::parseComma(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), and mlir::OpAsmParser::resolveOperands().
printAllReduceOperation()
static void printAllReduceOperation (AsmPrinter & printer, Operation * op, AllReduceOperationAttr attr) static
Definition at line 327 of file GPUDialect.cpp.
printAsyncDependencies()
static void printAsyncDependencies (OpAsmPrinter & printer, Operation * op, Type asyncTokenType, OperandRange asyncDependencies) static
Definition at line 1055 of file GPUDialect.cpp.
References verify().
printAttributions()
static void printAttributions (OpAsmPrinter & p, StringRef keyword, ArrayRef< BlockArgument > values) static
Definition at line 868 of file GPUDialect.cpp.
References mlir::Value::getType(), mlir::function_interface_impl::getTypeAttrName(), mlir::Type::isa(), print(), mlir::function_interface_impl::printFunctionAttributes(), mlir::function_interface_impl::printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), and mlir::success().
printLaunchFuncOperands()
static void printLaunchFuncOperands (OpAsmPrinter & printer, Operation * , OperandRange operands, TypeRange types) static
Definition at line 685 of file GPUDialect.cpp.
References mlir::Block::addArgument(), mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::OpBuilder::create(), mlir::Region::getBlocks(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_interface_impl::getTypeAttrName(), mlir::NamedAttribute::getValue(), mlir::OperationState::location, mlir::OpAsmPrinter::printOperand(), mlir::AsmPrinter::printType(), and value.
printSizeAssignment()
static void printSizeAssignment (OpAsmPrinter & p, KernelDim3 size, KernelDim3 operands, KernelDim3 ids) static
Definition at line 445 of file GPUDialect.cpp.
References print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
verify()
static LogicalResult verify (AllocOp op) static
Definition at line 1177 of file GPUDialect.cpp.
References mlir::RewritePatternSet::add(), mlir::failure(), mlir::RewriterBase::replaceOp(), and mlir::success().
Referenced by acceptBitWidth(), mlir::gpu::addAsyncDependency(), buildLLVMFunctionType(), mlir::pdl::PDLType::classof(), mlir::BoolAttr::classof(), mlir::DenseIntElementsAttr::classof(), computeMemRefRankReductionMask(), concatElemAndIndices(), eachHasOnlyOneOfTypes(), findDuplicateElement(), mlir::AffineDmaWaitOp::fold(), foldTransferInBoundsAttribute(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), getF64Values(), getGetValueTypeOpValueType(), getInsertExtractValueElementType(), getLoadStoreElementType(), getNumElements(), mlir::scf::getParallelForInductionVarOwner(), hasAtMostSingleNonScalar(), hasOneBranchOpTo(), inferExtractOpResultType(), inferStridedSliceOpResultType(), mlir::scf::insideMutuallyExclusiveBranches(), invertPredicate(), mlir::vector::isBroadcastableTo(), isComputeOperation(), isLastMemrefDimUnitStride(), isMatchingWidth(), isShapePreserving(), mlir::TensorType::isValidElementType(), isValidQuantizationSpec(), isZeroAttribute(), joinShapes(), lookupSymbolInModule(), makeI64ArrayAttr(), FoldLaunchArguments::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), SelectToExtUI::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::LLVM::LLVMFunctionType::params(), parseClauses(), parseGlobalMemrefOpTypeAndInitialValue(), parseInferType(), poolingInferReturnTypes(), populateFromInt64AttrArray(), printAllocateAndAllocator(), printAsyncDependencies(), printAtomicReductionRegion(), printAwaitResultType(), printCreateOperationOpAttributes(), printFillOpRegion(), printGEPIndices(), printNVVMIntrinsicOp(), printResultsValueType(), printSwitchOpCases(), printTransferAttrs(), produceSliceErrorMsg(), produceSubViewErrorMsg(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), mlir::FloatType::scaleElementBitwidth(), mlir::MemRefType::Builder::setMemorySpace(), impl::MemRefDataVerifier< T >::verify(), verifyAccessChain(), verifyAllocLikeOp(), verifyAtomicCompareExchangeImpl(), verifyAttributions(), verifyConstantType(), verifyConvOp(), verifyCoopMatrixMulAdd(), verifyDimAndSymbolIdentifiers(), verifyGenericOp(), verifyInsertSliceOp(), verifyMemoryOpIndexing(), verifyMemoryOpMetadata(), verifyMultShape(), verifyPointerAndCoopMatrixType(), verifyReshapeOp(), verifyResultTypesAreInferrable(), verifyTensorReshapeOp(), verifyVectorMemoryOp(), verifyYield(), and visit().
verifyAttributions()
static LogicalResult verifyAttributions (Operation * op, ArrayRef< BlockArgument > attributions, unsigned memorySpace) static
Definition at line 913 of file GPUDialect.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::getElementTypeOrSelf(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Value::getType(), mlir::OperationState::location, mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseSymbolName(), print(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), mlir::NamedAttrList::push_back(), mlir::success(), verify(), and mlir::verifyCompatibleShape().