MLIR: mlir::linalg::comprehensive_bufferize::linalg_ext Namespace Reference
mlir::linalg::comprehensive_bufferize::linalg_ext Namespace Reference
Typedefs
using AnchorMatchFn = std::function< bool(OpOperand &, SmallVector< Value > &)>
A function that matches anchor OpOperands for InitTensorOp elimination.
using RewriteFn = std::function< Value(OpBuilder &, Location, OpOperand &)>
A function that rewrites matched anchors.
Functions
LogicalResult eliminateInitTensors (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, AnchorMatchFn anchorMatchFunc, RewriteFn rewriteFunc, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside op.
LogicalResult insertSliceAnchoredInitTensorEliminationStep (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside op that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
Typedef Documentation
AnchorMatchFn
using mlir::linalg::comprehensive_bufferize::linalg_ext::AnchorMatchFn = typedef std::function<bool(OpOperand &, SmallVector<Value> &)>
A function that matches anchor OpOperands for InitTensorOp elimination.
If an OpOperand is matched, the function should populate the SmallVector with all values that are needed during RewriteFn to produce the replacement value.
Definition at line 25 of file LinalgInterfaceImpl.h.
RewriteFn
using mlir::linalg::comprehensive_bufferize::linalg_ext::RewriteFn = typedef std::function<Value(OpBuilder &, Location, OpOperand &)>
A function that rewrites matched anchors.
Definition at line 28 of file LinalgInterfaceImpl.h.
Function Documentation
eliminateInitTensors()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::eliminateInitTensors (Operation * op, bufferization::BufferizationState & state, bufferization::BufferizationAliasInfo & aliasInfo, AnchorMatchFn anchorMatchFunc, RewriteFn rewriteFunc, SmallVector< Operation *> & newOps)
Try to eliminate InitTensorOps inside op.
rewriteFunc generates the replacement for the InitTensorOp.
Only InitTensorOps that are anchored on a matching OpOperand as per anchorMatchFunc are considered. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
The result of rewriteFunc must usually be analyzed for inplacability. This analysis can be skipped with skipAnalysis.
An InitTensorOp is replaced with the the result of rewriteFunc if it is anchored on a matching OpOperand. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
Definition at line 533 of file LinalgInterfaceImpl.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::bufferization::BufferizationAliasInfo::createAliasInfoEntry(), mlir::Value::dyn_cast(), mlir::failure(), findValidInsertionPoint(), mlir::bufferization::BufferizationState::findValueInReverseUseDefChain(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::bufferization::BufferizationState::getAliasingOpOperand(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Operation::getOpOperands(), insertSliceAnchoredInitTensorEliminationStep(), mlir::bufferization::BufferizationAliasInfo::isInPlace(), mlir::Value::replaceAllUsesWith(), mlir::WalkResult::skip(), mlir::bufferization::BufferizationAliasInfo::unionAliasSets(), mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses(), and mlir::Operation::walk().
Referenced by insertSliceAnchoredInitTensorEliminationStep().
insertSliceAnchoredInitTensorEliminationStep()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::insertSliceAnchoredInitTensorEliminationStep (Operation * op, bufferization::BufferizationState & state, bufferization::BufferizationAliasInfo & aliasInfo, SmallVector< Operation *> & newOps)
Try to eliminate InitTensorOps inside op that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
Try to eliminate InitTensorOps inside op.
An InitTensorOp can be eliminated if it is eventually inserted into another tensor (and some other conditions are met).
E.g.: %0 = linalg.init_tensor %1 = linalg.fill(cst, %0) {inplace = [true]} %2 = tensor.insert_slice %1 into t[10][20][1]
InitTensorOp elimination will try to fill t inplace instead of filling a new allocation %0 and inserting it into t. This is done by replacing the InitTensorOp with:
%0 = tensor.extract_slice t[10][20][1]
The analysis looks for matching ExtractSliceOp/InsertSliceOp pairs and lets those bufferize inplace in the absence of other conflicts.
Starting from an InsertSliceOp, an InitTensorOp at the end of the insert source's reverse use-def chain is eliminated if:
The InsertSliceOp was decided to bufferize inplace.
On the reverse use-def chain path from the InsertSliceOp to the InitTensorOp, all ops were decided to bufferize inplace and the buffer relation is "equivalent" (TODO: can be relaxed if needed).
The reverse use-def chain has exactly one end, which is the InitTensorOp.
Note that the newly inserted ExtractSliceOp may have to bufferize out-of-place due to RaW conflicts.
Definition at line 636 of file LinalgInterfaceImpl.cpp.
References mlir::OpBuilder::create(), eliminateInitTensors(), mlir::Builder::getIndexAttr(), mlir::detail::IROperandBase::getOwner(), mlir::bufferization::BufferizationAliasInfo::isInPlace(), and registerBufferizableOpInterfaceExternalModels().
Referenced by allocationFnUsingAlloca(), and eliminateInitTensors().
registerBufferizableOpInterfaceExternalModels()
void mlir::linalg::comprehensive_bufferize::linalg_ext::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 692 of file LinalgInterfaceImpl.cpp.
References mlir::DialectRegistry::addOpInterface().
Referenced by insertSliceAnchoredInitTensorEliminationStep().