MLIR: lib/Conversion/TosaToLinalg/TosaToLinalgNamed.cpp File Reference
TosaToLinalgNamed.cpp File Reference
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tensor/Utils/Utils.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Tosa/Utils/CoversionUtils.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <numeric>
Functions
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder &rewriter)
Function Documentation
applyPad()
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder & rewriter) static
Definition at line 34 of file TosaToLinalgNamed.cpp.
References mlir::Attribute::cast(), mlir::Location::cast(), mlir::Type::cast(), mlir::tosa::checkHasDynamicBatchDims(), clamp(), mlir::tosa::condenseValues(), mlir::OpBuilder::create(), mlir::tensor::createPadScalarOp(), mlir::failure(), mlir::AffineMap::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), getElementType(), mlir::Builder::getFloatAttr(), mlir::FloatType::getFloatSemantics(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Builder::getI8IntegerAttr(), mlir::Builder::getIndexAttr(), mlir::Builder::getIntegerAttr(), mlir::Builder::getMultiDimIdentityMap(), mlir::tosa::getNParallelLoopsAttrs(), mlir::Value::getType(), mlir::tosa::getValuesFromIntArrayAttribute(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), max(), min(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::RewriterBase::notifyMatchFailure(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().